window.PLAN_DATA = {
  "version": "2026.09.18-18",
  "semester": {
    "title": "Cronograma · segundo semestre 2026",
    "start": "2026-08-03",
    "end": "2026-11-30"
  },
  "subjects": {
    "fuaa": {
      "name": "Fundamentos de Aprendizaje Automático",
      "short": "FuAA",
      "color": "#8cff3a",
      "status": "Cronograma oficial actualizado · lectura por libro",
      "source": "FuAA 2026 · cronograma actualizado",
      "scheduleUrl": "https://eva.fing.edu.uy/pluginfile.php/71926/mod_label/intro/FuAA_2026_cronograma.pdf?time=1785277006380",
      "scheduleLabel": "Cronograma oficial",
      "scheduleOriginal": true
    },
    "redes": {
      "name": "Redes de Computadoras",
      "short": "Redes",
      "color": "#36a9ff",
      "status": "Cronograma oficial cargado",
      "source": "Cronograma Redes 2026",
      "scheduleUrl": "cronogramas/Cronograma_redes_2026.pdf",
      "scheduleLabel": "Cronograma oficial",
      "scheduleOriginal": true
    },
    "fbd": {
      "name": "Fundamentos de Bases de Datos",
      "short": "FBD",
      "color": "#ff9a3c",
      "status": "Cronograma oficial cargado",
      "source": "Cronograma FBD 2026 proporcionado",
      "scheduleUrl": "https://eva.fing.edu.uy/course/view.php?id=330&section=3#tabs-tree-start",
      "scheduleLabel": "Cronograma oficial",
      "scheduleOriginal": true
    },
    "pln": {
      "name": "Introducción al Procesamiento de Lenguaje Natural",
      "short": "IntroPLN",
      "color": "#ff4fcf",
      "status": "Cronograma tentativo 2026 + clases OpenFing cargadas",
      "source": "Cronograma tentativo PLN 2026 + OpenFing",
      "scheduleUrl": "https://eva.fing.edu.uy/mod/page/view.php?id=84886",
      "scheduleLabel": "Cronograma oficial",
      "scheduleOriginal": true
    }
  },
  "typeLabels": {
    "openfing": "Clase OpenFing",
    "reading": "Lectura",
    "practical": "Práctico",
    "course-class": "Actividad del curso",
    "discussion": "Discusión",
    "control": "Control",
    "questionnaire": "Cuestionario",
    "workshop": "Taller",
    "partial": "Parcial",
    "partial-window": "Período de parciales",
    "assignment-published": "Publicación de obligatorio",
    "deadline": "Entrega",
    "monitoring": "Monitoreo",
    "defense": "Defensa",
    "holiday": "Feriado",
    "no-class": "Sin clase",
    "consultation": "Consulta",
    "notice": "Pendiente",
    "study": "Estudio parcial"
  },
  "typeMarks": {
    "openfing": "OF",
    "reading": "LIBRO",
    "practical": "P",
    "course-class": "CLASE",
    "discussion": "DISC",
    "control": "CTRL",
    "questionnaire": "CP",
    "workshop": "TALLER",
    "partial": "PARCIAL",
    "partial-window": "PARCIALES",
    "assignment-published": "OB",
    "deadline": "ENTREGA",
    "monitoring": "LAB",
    "defense": "DEF",
    "holiday": "FERIADO",
    "no-class": "—",
    "consultation": "CONSULTA",
    "notice": "PEND.",
    "study": "ESTUDIO"
  },
  "items": [
    {
      "id": "redes-20260914-05",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P5",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 530
    },
    {
      "id": "fuaa-20260914-01",
      "week": "2026-09-28",
      "eventDate": "",
      "subject": "fuaa",
      "type": "reading",
      "title": "Tema 12 · Validación",
      "details": "Libro · sección 4.3 · Reubicado para después del primer parcial del 23/09; no entra en ese parcial.",
      "source": "FuAA 2026 · temario y libro",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1805
    },
    {
      "id": "fuaa-20260914-04",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "fuaa",
      "type": "control",
      "title": "Control 3",
      "details": "Temas 8, 9, 10 y 11",
      "source": "FuAA 2026",
      "fixed": true,
      "important": true,
      "priority": "high",
      "order": 1700
    },
    {
      "id": "fuaa-20260914-05",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 4",
      "details": "Temas 10, 11 y 12",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1710
    },
    {
      "id": "fuaa-20260914-06",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP06",
      "details": "Vinculado al Práctico 4",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1720
    },
    {
      "id": "fbd-20260914-01",
      "week": "2026-09-14",
      "periodLabel": "Semana 7 · 14/09–18/09",
      "eventDate": "",
      "subject": "fbd",
      "type": "course-class",
      "title": "Diseño Relacional · Normalización",
      "details": "Tema teórico indicado en el cronograma",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2270
    },
    {
      "id": "fbd-20260914-02",
      "week": "2026-09-14",
      "periodLabel": "Semana 7 · 14/09–18/09",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 13",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2280
    },
    {
      "id": "fbd-20260914-03",
      "week": "2026-09-14",
      "periodLabel": "Semana 7 · 14/09–18/09",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 14",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2290
    },
    {
      "id": "fbd-20260914-04",
      "week": "2026-09-14",
      "periodLabel": "Semana 7 · 14/09–18/09",
      "eventDate": "",
      "subject": "fbd",
      "type": "practical",
      "title": "Prácticos 2, 3 y 4",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2300
    },
    {
      "id": "fuaa-20260921-02",
      "week": "2026-09-21",
      "eventDate": "2026-09-23",
      "subject": "fuaa",
      "type": "partial",
      "title": "Primer parcial",
      "details": "",
      "source": "FuAA 2026",
      "fixed": true,
      "important": true,
      "priority": "critical",
      "order": 1740
    },
    {
      "id": "fbd-20260921-01",
      "week": "2026-09-28",
      "periodLabel": "Lunes 28/09",
      "eventDate": "2026-09-28",
      "subject": "fbd",
      "type": "partial",
      "title": "Primer parcial",
      "details": "Primer parcial de FBD · contenido de la primera parte del semestre.",
      "source": "Fecha de parcial informada",
      "fixed": true,
      "important": true,
      "priority": "critical",
      "order": 2310
    },
    {
      "id": "redes-20261005-04",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P5 · RDT, control de congestión y TCP",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 640
    },
    {
      "id": "fuaa-20261005-01",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "fuaa",
      "type": "reading",
      "title": "Tema 13 · Epílogo de los fundamentos teóricos",
      "details": "Libro · secciones 5.1, 5.2, 5.3",
      "source": "FuAA 2026 · temario y libro",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1380
    },
    {
      "id": "fuaa-20261005-02",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "fuaa",
      "type": "reading",
      "title": "Tema 14 · Perceptrón multicapa",
      "details": "Libro · secciones 7.1, 7.2",
      "source": "FuAA 2026 · temario y libro",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1390
    },
    {
      "id": "fuaa-20261005-03",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "fuaa",
      "type": "reading",
      "title": "Tema 15 · Redes neuronales",
      "details": "Libro · secciones 7.3, 7.4, 7.5, 7.6",
      "source": "FuAA 2026 · temario y libro",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1400
    },
    {
      "id": "fuaa-20261005-06",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 5 / scikit-learn",
      "details": "Temas 14 y 15",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1770
    },
    {
      "id": "fuaa-20261005-07",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP07",
      "details": "Vinculado al Práctico 5",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1780
    },
    {
      "id": "fbd-20261005-01",
      "week": "2026-10-05",
      "periodLabel": "Semana 10 · 05/10–11/10",
      "eventDate": "",
      "subject": "fbd",
      "type": "course-class",
      "title": "Diseño Relacional · Normalización",
      "details": "Tema teórico indicado en el cronograma",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2320
    },
    {
      "id": "fbd-20261005-02",
      "week": "2026-10-05",
      "periodLabel": "Semana 10 · 05/10–11/10",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 13",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2330
    },
    {
      "id": "fbd-20261005-03",
      "week": "2026-10-05",
      "periodLabel": "Semana 10 · 05/10–11/10",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 14",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2340
    },
    {
      "id": "fbd-20261005-04",
      "week": "2026-10-05",
      "periodLabel": "Semana 10 · 05/10–11/10",
      "eventDate": "",
      "subject": "fbd",
      "type": "practical",
      "title": "Práctico 5 · Dependencias funcionales",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2350
    },
    {
      "id": "redes-20261012-05",
      "week": "2026-10-12",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P6 · Direccionamiento, numeración, forwarding y LPM",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 720
    },
    {
      "id": "fuaa-20261012-02",
      "week": "2026-10-12",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 5",
      "details": "Temas 14 y 15",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1800
    },
    {
      "id": "fuaa-20261012-03",
      "week": "2026-10-12",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP08",
      "details": "Vinculado al Práctico 5",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1810
    },
    {
      "id": "fbd-20261012-01",
      "week": "2026-10-12",
      "periodLabel": "Semana 11 · 12/10–18/10",
      "eventDate": "",
      "subject": "fbd",
      "type": "course-class",
      "title": "Diseño Relacional (DMVs)",
      "details": "Tema teórico indicado en el cronograma",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2360
    },
    {
      "id": "fbd-20261012-02",
      "week": "2026-10-12",
      "periodLabel": "Semana 11 · 12/10–18/10",
      "eventDate": "",
      "subject": "fbd",
      "type": "course-class",
      "title": "Pasaje de MER a MR",
      "details": "Tema teórico indicado en el cronograma",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2370
    },
    {
      "id": "fbd-20261012-03",
      "week": "2026-10-12",
      "periodLabel": "Semana 11 · 12/10–18/10",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 15",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2380
    },
    {
      "id": "fbd-20261012-04",
      "week": "2026-10-12",
      "periodLabel": "Semana 11 · 12/10–18/10",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 16",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2390
    },
    {
      "id": "fbd-20261012-05",
      "week": "2026-10-12",
      "periodLabel": "Semana 11 · 12/10–18/10",
      "eventDate": "",
      "subject": "fbd",
      "type": "practical",
      "title": "Práctico 6 · Normalización",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2400
    },
    {
      "id": "redes-20261019-06",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P6",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 810
    },
    {
      "id": "fuaa-20261019-01",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "fuaa",
      "type": "reading",
      "title": "Tema 16 · Máquinas de vectores de soporte",
      "details": "Libro · secciones 8.1, 8.2",
      "source": "FuAA 2026 · temario y libro",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1420
    },
    {
      "id": "fuaa-20261019-02",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "fuaa",
      "type": "reading",
      "title": "Tema 17 · Métodos de Kernel",
      "details": "Libro · secciones 8.3, 8.4",
      "source": "FuAA 2026 · temario y libro",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1430
    },
    {
      "id": "fuaa-20261019-05",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "fuaa",
      "type": "control",
      "title": "Control 4",
      "details": "Temas 14 y 15",
      "source": "FuAA 2026",
      "fixed": true,
      "important": true,
      "priority": "high",
      "order": 1830
    },
    {
      "id": "fuaa-20261019-06",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 6",
      "details": "Temas 16 y 17",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1840
    },
    {
      "id": "fuaa-20261019-07",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP09",
      "details": "Vinculado al Práctico 6",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1850
    },
    {
      "id": "fbd-20261019-01",
      "week": "2026-10-19",
      "periodLabel": "Semana 12 · 19/10–25/10",
      "eventDate": "",
      "subject": "fbd",
      "type": "course-class",
      "title": "Estrategia de acceso a datos",
      "details": "Tema teórico indicado en el cronograma",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2410
    },
    {
      "id": "fbd-20261019-02",
      "week": "2026-10-19",
      "periodLabel": "Semana 12 · 19/10–25/10",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 17",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2420
    },
    {
      "id": "fbd-20261019-03",
      "week": "2026-10-19",
      "periodLabel": "Semana 12 · 19/10–25/10",
      "eventDate": "",
      "subject": "fbd",
      "type": "practical",
      "title": "Práctico 7 · Dependencias Multivaluadas",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2430
    },
    {
      "id": "redes-20261026-05",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P7 · Enrutamiento (DV y LS), OSPF y BGP",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 890
    },
    {
      "id": "fuaa-20261026-01",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "fuaa",
      "type": "reading",
      "title": "Tema 18 · Métodos basados en similitud",
      "details": "Libro · secciones 6.1, 6.2, 6.3",
      "source": "FuAA 2026 · temario y libro",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1450
    },
    {
      "id": "fuaa-20261026-02",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "fuaa",
      "type": "reading",
      "title": "Tema 19 · Aprendizaje no supervisado",
      "details": "Libro · secciones 6.3, 6.4",
      "source": "FuAA 2026 · temario y libro",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1460
    },
    {
      "id": "fuaa-20261026-05",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "fuaa",
      "type": "control",
      "title": "Control 5",
      "details": "Temas 16 y 17",
      "source": "FuAA 2026",
      "fixed": true,
      "important": true,
      "priority": "high",
      "order": 1870
    },
    {
      "id": "fuaa-20261026-06",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 6",
      "details": "Temas 16 y 17",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1880
    },
    {
      "id": "fuaa-20261026-07",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP10",
      "details": "Vinculado al Práctico 6",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1890
    },
    {
      "id": "fbd-20261026-01",
      "week": "2026-10-26",
      "periodLabel": "Semana 13 · 26/10–01/11",
      "eventDate": "",
      "subject": "fbd",
      "type": "course-class",
      "title": "Optimización",
      "details": "Tema teórico indicado en el cronograma",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2440
    },
    {
      "id": "fbd-20261026-02",
      "week": "2026-10-26",
      "periodLabel": "Semana 13 · 26/10–01/11",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 18",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2450
    },
    {
      "id": "fbd-20261026-03",
      "week": "2026-10-26",
      "periodLabel": "Semana 13 · 26/10–01/11",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 19",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2460
    },
    {
      "id": "fbd-20261026-04",
      "week": "2026-10-26",
      "periodLabel": "Semana 13 · 26/10–01/11",
      "eventDate": "",
      "subject": "fbd",
      "type": "practical",
      "title": "Práctico 8 · Pasaje de MER a MR",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2470
    },
    {
      "id": "redes-20261102-05",
      "week": "2026-11-02",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P7",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 970
    },
    {
      "id": "fuaa-20261102-02",
      "week": "2026-11-02",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 7",
      "details": "Temas 18, 19 y 20",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1910
    },
    {
      "id": "fuaa-20261102-03",
      "week": "2026-11-02",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP11",
      "details": "Vinculado al Práctico 7",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1920
    },
    {
      "id": "fbd-20261102-01",
      "week": "2026-11-02",
      "periodLabel": "Semana 14 · 02/11–08/11",
      "eventDate": "",
      "subject": "fbd",
      "type": "course-class",
      "title": "Concurrencia",
      "details": "Tema teórico indicado en el cronograma",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2480
    },
    {
      "id": "fbd-20261102-02",
      "week": "2026-11-02",
      "periodLabel": "Semana 14 · 02/11–08/11",
      "eventDate": "",
      "subject": "fbd",
      "type": "course-class",
      "title": "Recuperación",
      "details": "Tema teórico indicado en el cronograma",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2490
    },
    {
      "id": "fbd-20261102-03",
      "week": "2026-11-02",
      "periodLabel": "Semana 14 · 02/11–08/11",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 20",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2500
    },
    {
      "id": "fbd-20261102-04",
      "week": "2026-11-02",
      "periodLabel": "Semana 14 · 02/11–08/11",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Video OpenFing 21",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2510
    },
    {
      "id": "fbd-20261102-05",
      "week": "2026-11-02",
      "periodLabel": "Semana 14 · 02/11–08/11",
      "eventDate": "",
      "subject": "fbd",
      "type": "practical",
      "title": "Práctico 9 · Optimización",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2520
    },
    {
      "id": "redes-20261109-05",
      "week": "2026-11-09",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P8 y P9 · Capa de enlace",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1050
    },
    {
      "id": "fuaa-20261109-01",
      "week": "2026-11-09",
      "eventDate": "",
      "subject": "fuaa",
      "type": "reading",
      "title": "Tema 20 · Ingeniería de características",
      "details": "Tema del temario oficial · sin sección del libro indicada en el cronograma",
      "source": "FuAA 2026 · temario y libro",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1480
    },
    {
      "id": "fuaa-20261109-03",
      "week": "2026-11-09",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 7",
      "details": "Temas 18, 19 y 20",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1940
    },
    {
      "id": "fuaa-20261109-04",
      "week": "2026-11-09",
      "eventDate": "",
      "subject": "fuaa",
      "type": "control",
      "title": "Control 6",
      "details": "Temas 18, 19 y 20",
      "source": "FuAA 2026",
      "fixed": true,
      "important": true,
      "priority": "high",
      "order": 1950
    },
    {
      "id": "fuaa-20261109-05",
      "week": "2026-11-09",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP12",
      "details": "Vinculado al Práctico 7",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1960
    },
    {
      "id": "fbd-20261109-01",
      "week": "2026-11-09",
      "periodLabel": "Semana 15 · 09/11–15/11",
      "eventDate": "",
      "subject": "fbd",
      "type": "course-class",
      "title": "Repaso",
      "details": "Tema teórico indicado en el cronograma",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2530
    },
    {
      "id": "fbd-20261109-02",
      "week": "2026-11-09",
      "periodLabel": "Semana 15 · 09/11–15/11",
      "eventDate": "",
      "subject": "fbd",
      "type": "practical",
      "title": "Práctico 10 · Concurrencia y Recuperación",
      "details": "",
      "source": "Cronograma FBD 2026 proporcionado",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2540
    },
    {
      "id": "redes-20261116-05",
      "week": "2026-11-16",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P9",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1140
    },
    {
      "id": "pln-presentacion-articulos-17",
      "week": "2026-11-16",
      "periodLabel": "Semana 13 · 17/11 y 19/11",
      "eventDate": "2026-11-17",
      "subject": "pln",
      "type": "defense",
      "title": "Presentaciones de artículos · 17/11",
      "details": "Salones a confirmar.",
      "source": "Cronograma tentativo PLN 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 3230
    },
    {
      "id": "pln-presentacion-articulos-19",
      "week": "2026-11-16",
      "periodLabel": "Semana 13 · 17/11 y 19/11",
      "eventDate": "2026-11-19",
      "subject": "pln",
      "type": "defense",
      "title": "Presentaciones de artículos · 19/11",
      "details": "Salones a confirmar.",
      "source": "Cronograma tentativo PLN 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 3240
    },
    {
      "id": "fuaa-20261123-01",
      "week": "2026-11-23",
      "eventDate": "2026-11-23",
      "subject": "fuaa",
      "type": "partial",
      "title": "Segundo parcial",
      "details": "",
      "source": "FuAA 2026",
      "fixed": true,
      "important": true,
      "priority": "critical",
      "order": 1990
    },
    {
      "id": "fuaa-20261123-02",
      "week": "2026-11-23",
      "eventDate": "",
      "subject": "fuaa",
      "type": "partial-window",
      "title": "Período de parciales",
      "details": "",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2000
    },
    {
      "id": "pln-prueba-1",
      "week": "2026-09-28",
      "periodLabel": "Martes 29/09",
      "eventDate": "2026-09-29",
      "subject": "pln",
      "type": "partial",
      "title": "Prueba 1 / primer parcial",
      "details": "Primer parcial de IntroPLN · hasta Semántica.",
      "source": "Fecha de parcial informada",
      "fixed": true,
      "important": true,
      "priority": "critical",
      "order": 3110
    },
    {
      "id": "pln-prueba-2",
      "week": "",
      "periodLabel": "",
      "eventDate": "",
      "subject": "pln",
      "type": "partial",
      "title": "Prueba 2 / 2dos parciales · fecha no indicada",
      "details": "El cronograma tentativo no indica una fecha concreta.",
      "source": "Cronograma tentativo PLN 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 3250
    },
    {
      "id": "plan-fbd-entregable-20260920",
      "week": "2026-09-14",
      "eventDate": "2026-09-20",
      "subject": "fbd",
      "type": "deadline",
      "title": "Entregable FBD · terminar y entregar",
      "details": "Cerrar el entregable actual: probar consultas sobre una base limpia y revisar álgebra, cálculo relacional y SQL antes de entregar.",
      "periodLabel": "Antes del domingo 20/09",
      "source": "Plan de parciales",
      "fixed": false,
      "important": true,
      "priority": "critical",
      "order": 950
    },
    {
      "id": "plan-fuaa-cierre-teoria-p1",
      "week": "2026-09-14",
      "eventDate": "2026-09-22",
      "subject": "fuaa",
      "type": "study",
      "title": "FuAA · cerrar teoría del primer parcial",
      "details": "Temas 1–11, hasta Regularización. Validación queda fuera. Priorizar generalización/VC, sesgo-varianza, regresión lineal y logística, descenso por gradiente/SGD, sobreajuste y regularización.",
      "periodLabel": "Cerrar antes del parcial",
      "source": "Plan de parciales",
      "fixed": false,
      "important": true,
      "priority": "critical",
      "order": 960
    },
    {
      "id": "plan-fuaa-practicos-p1",
      "week": "2026-09-14",
      "eventDate": "2026-09-22",
      "subject": "fuaa",
      "type": "study",
      "title": "FuAA · reconstruir núcleo de prácticos",
      "details": "Revisar P1–P4 sin rehacer todo: costo → gradiente → actualización, BGD/SGD, regresión logística, vectorización y shapes de NumPy. Priorizar lo que todavía no sale sin material.",
      "periodLabel": "Antes del 23/09",
      "source": "Plan de parciales",
      "fixed": false,
      "important": true,
      "priority": "high",
      "order": 970
    },
    {
      "id": "plan-fuaa-simulacro-p1",
      "week": "2026-09-14",
      "eventDate": "2026-09-22",
      "subject": "fuaa",
      "type": "study",
      "title": "FuAA · parcial viejo / simulacro final",
      "details": "Resolver uno con tiempo y corregir únicamente los huecos que aparezcan. Cerrar el estudio el 22; el parcial es el 23/09 a las 08:00.",
      "periodLabel": "Cierre 22/09",
      "source": "Plan de parciales",
      "fixed": false,
      "important": true,
      "priority": "high",
      "order": 980
    },
    {
      "id": "plan-redes-transporte-p1",
      "week": "2026-09-14",
      "eventDate": "2026-09-22",
      "subject": "redes",
      "type": "study",
      "title": "Redes · OpenFing 8–11 · Transporte",
      "details": "Ver las clases 8, 9, 10 y 11. Foco en RDT, pipelining, GBN/SR, TCP, RTT/ACK, control de flujo y congestión. Aplicación ya fue vista; no volver a rehacerla completa.",
      "periodLabel": "Antes del 23/09",
      "source": "Plan de parciales",
      "fixed": false,
      "important": true,
      "priority": "critical",
      "order": 990
    },
    {
      "id": "plan-redes-practicos-p1",
      "week": "2026-09-14",
      "eventDate": "2026-09-22",
      "subject": "redes",
      "type": "study",
      "title": "Redes · P4 DNS/Email + P5 RDT/TCP/congestión",
      "details": "P4: reforzar especialmente jerarquía DNS. P5 es la máxima prioridad. P3 sockets queda como repaso rápido porque el obligatorio ya dio práctica con UDP/TCP y sockets.",
      "periodLabel": "Antes del 23/09",
      "source": "Plan de parciales",
      "fixed": false,
      "important": true,
      "priority": "critical",
      "order": 1000
    },
    {
      "id": "plan-redes-simulacro-p1",
      "week": "2026-09-14",
      "eventDate": "2026-09-22",
      "subject": "redes",
      "type": "study",
      "title": "Redes · parcial viejo / repaso final",
      "details": "Resolver un parcial o una selección equivalente y revisar errores de Transporte, DNS y TCP antes del miércoles.",
      "periodLabel": "Cierre 22/09",
      "source": "Plan de parciales",
      "fixed": false,
      "important": true,
      "priority": "high",
      "order": 1010
    },
    {
      "id": "redes-primer-parcial-20260923",
      "week": "2026-09-21",
      "eventDate": "2026-09-23",
      "subject": "redes",
      "type": "partial",
      "title": "Primer parcial",
      "details": "Introducción + Aplicación + Transporte hasta la sección 3.6; prácticos hasta P5.",
      "periodLabel": "Miércoles 23/09",
      "source": "Fecha de parcial informada",
      "fixed": false,
      "important": true,
      "priority": "critical",
      "order": 1020
    },
    {
      "id": "plan-fbd-mer-modelo-p1",
      "week": "2026-09-21",
      "eventDate": "2026-09-27",
      "subject": "fbd",
      "type": "study",
      "title": "FBD · MER + modelo relacional",
      "details": "Repasar diseño conceptual, MER, claves y restricciones. Aprovechar lo ya trabajado y concentrarse en justificar correctamente el modelado.",
      "periodLabel": "Antes del 28/09",
      "source": "Plan de parciales",
      "fixed": false,
      "important": true,
      "priority": "high",
      "order": 1100
    },
    {
      "id": "plan-fbd-consultas-p1",
      "week": "2026-09-21",
      "eventDate": "2026-09-27",
      "subject": "fbd",
      "type": "study",
      "title": "FBD · Álgebra + Cálculo + SQL",
      "details": "Rehacer consultas representativas en las tres formas. Incluir joins, proyección/diferencia, EXISTS/NOT EXISTS y cuantificación.",
      "periodLabel": "Antes del 28/09",
      "source": "Plan de parciales",
      "fixed": false,
      "important": true,
      "priority": "critical",
      "order": 1110
    },
    {
      "id": "plan-fbd-df-normalizacion-p1",
      "week": "2026-09-21",
      "eventDate": "2026-09-27",
      "subject": "fbd",
      "type": "study",
      "title": "FBD · Dependencias funcionales + Normalización",
      "details": "Cerrar los temas más nuevos de la primera parte: dependencias funcionales, claves/cierres y normalización.",
      "periodLabel": "Antes del 28/09",
      "source": "Plan de parciales",
      "fixed": false,
      "important": true,
      "priority": "critical",
      "order": 1120
    },
    {
      "id": "plan-fbd-simulacro-p1",
      "week": "2026-09-21",
      "eventDate": "2026-09-27",
      "subject": "fbd",
      "type": "study",
      "title": "FBD · parcial viejo / repaso final",
      "details": "Resolver un parcial o ejercicios representativos y usar los errores para el último repaso.",
      "periodLabel": "Cierre 27/09",
      "source": "Plan de parciales",
      "fixed": false,
      "important": true,
      "priority": "high",
      "order": 1130
    },
    {
      "id": "plan-pln-libro-cap2-p1",
      "week": "2026-09-21",
      "eventDate": "2026-09-28",
      "subject": "pln",
      "type": "reading",
      "title": "Libro · Cap. 2 — Análisis léxico, preprocesamiento y DME",
      "details": "Lectura marcada en el cronograma para la primera parte y todavía pendiente.",
      "periodLabel": "Antes del 29/09",
      "source": "Cronograma + plan de parciales",
      "fixed": false,
      "important": true,
      "priority": "critical",
      "order": 1140
    },
    {
      "id": "plan-pln-libro-sintaxis-p1",
      "week": "2026-09-21",
      "eventDate": "2026-09-28",
      "subject": "pln",
      "type": "reading",
      "title": "Libro · Sintaxis — caps. 18–19 / 19–20 según edición",
      "details": "Cronograma: capítulos 18 y 19 en la edición enero 2025, o 19 y 20 en la edición agosto 2026. Lectura todavía pendiente.",
      "periodLabel": "Antes del 29/09",
      "source": "Cronograma + plan de parciales",
      "fixed": false,
      "important": true,
      "priority": "critical",
      "order": 1150
    },
    {
      "id": "plan-pln-intro-gramatica-p1",
      "week": "2026-09-21",
      "eventDate": "2026-09-28",
      "subject": "pln",
      "type": "study",
      "title": "IntroPLN · repasar Introducción + Gramática",
      "details": "Repaso de los temas de las semanas 1 y 3 para cubrir toda la primera parte, no solo las lecturas nuevas.",
      "periodLabel": "Antes del 29/09",
      "source": "Plan de parciales",
      "fixed": false,
      "important": true,
      "priority": "high",
      "order": 1160
    },
    {
      "id": "plan-pln-semantica-p1",
      "week": "2026-09-21",
      "eventDate": "2026-09-28",
      "subject": "pln",
      "type": "study",
      "title": "IntroPLN · Semántica",
      "details": "Repasar el material de la clase presencial: Semántica y los conceptos de semántica léxica/roles semánticos que correspondan. El cronograma no asigna capítulo del libro para esta semana.",
      "periodLabel": "Antes del 29/09",
      "source": "Plan de parciales",
      "fixed": false,
      "important": true,
      "priority": "critical",
      "order": 1170
    },
    {
      "id": "plan-pln-simulacro-p1",
      "week": "2026-09-21",
      "eventDate": "2026-09-28",
      "subject": "pln",
      "type": "study",
      "title": "IntroPLN · repaso final / Prueba 1",
      "details": "Cerrar Análisis léxico, Sintaxis y Semántica y revisar preguntas o material de evaluación disponible.",
      "periodLabel": "Cierre 28/09",
      "source": "Plan de parciales",
      "fixed": false,
      "important": true,
      "priority": "high",
      "order": 1180
    },
    {
      "id": "redes-20260907-02",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 8",
      "details": "Transporte · reubicada a la semana de preparación del primer parcial",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 500
    },
    {
      "id": "redes-20260907-03",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 9",
      "details": "Transporte · reubicada a la semana de preparación del primer parcial",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 505
    },
    {
      "id": "redes-20260914-02",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 10",
      "details": "Asignada dentro de Transporte",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 500
    },
    {
      "id": "redes-20260914-03",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 11",
      "details": "Asignada dentro de Transporte",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 510
    },
    {
      "id": "redes-20261005-02",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 11 · continuación",
      "details": "Transporte · tramo del cronograma posterior al primer parcial (cap. 3 hasta el final)",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 620
    },
    {
      "id": "redes-20261012-02",
      "week": "2026-10-12",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 12",
      "details": "Asignada dentro de Red: plano de datos",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 690
    },
    {
      "id": "redes-20261012-03",
      "week": "2026-10-12",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 13",
      "details": "Asignada dentro de Red: plano de datos",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 700
    },
    {
      "id": "redes-20261019-02",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 14",
      "details": "Asignada dentro de Red: IPv6",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 770
    },
    {
      "id": "redes-20261019-03",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 18",
      "details": "Asignada dentro de Red: IPv6",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 780
    },
    {
      "id": "redes-20261019-04",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 19",
      "details": "Asignada dentro de Red: IPv6",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 790
    },
    {
      "id": "redes-20261026-02",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 14",
      "details": "Asignada dentro de Red: plano de control",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 860
    },
    {
      "id": "redes-20261026-03",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 15",
      "details": "Asignada dentro de Red: plano de control",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 870
    },
    {
      "id": "redes-20261102-02",
      "week": "2026-11-02",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 16",
      "details": "Asignada dentro de Red: plano de control",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 940
    },
    {
      "id": "redes-20261102-03",
      "week": "2026-11-02",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 17",
      "details": "Asignada dentro de Red: plano de control",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 950
    },
    {
      "id": "redes-20261109-02",
      "week": "2026-11-09",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 20",
      "details": "Asignada dentro de Enlace",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1020
    },
    {
      "id": "redes-20261109-03",
      "week": "2026-11-09",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 21",
      "details": "Asignada dentro de Enlace",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1030
    },
    {
      "id": "redes-20261116-02",
      "week": "2026-11-16",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 22",
      "details": "Asignada dentro de Enlace",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1110
    },
    {
      "id": "redes-20261116-03",
      "week": "2026-11-16",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 23",
      "details": "Asignada dentro de Enlace",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1120
    },
    {
      "id": "pln-openfing-13",
      "week": "2026-09-14",
      "periodLabel": "Semana 06 · 15/09",
      "eventDate": "2026-09-15",
      "subject": "pln",
      "type": "course-class",
      "title": "Semántica",
      "details": "Clase presencial · tema del cronograma tentativo 2026",
      "source": "Cronograma tentativo PLN 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 3090
    },
    {
      "id": "pln-openfing-09",
      "week": "2026-10-05",
      "periodLabel": "Semana 07 · 06/10",
      "eventDate": "2026-10-06",
      "subject": "pln",
      "type": "course-class",
      "title": "Aprendizaje Automático para PLN · Clasificación",
      "details": "Clase presencial · tema del cronograma tentativo 2026",
      "source": "Cronograma tentativo PLN 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 3130
    },
    {
      "id": "pln-openfing-15",
      "week": "2026-10-12",
      "periodLabel": "Semana 08 · 13/10",
      "eventDate": "2026-10-13",
      "subject": "pln",
      "type": "course-class",
      "title": "Word embeddings · Redes Neuronales",
      "details": "Clase presencial · tema del cronograma tentativo 2026",
      "source": "Cronograma tentativo PLN 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 3150
    },
    {
      "id": "pln-openfing-07",
      "week": "2026-10-19",
      "periodLabel": "Semana 09 · 20/10",
      "eventDate": "2026-10-20",
      "subject": "pln",
      "type": "course-class",
      "title": "Modelos de Lenguaje",
      "details": "Clase presencial · tema del cronograma tentativo 2026",
      "source": "Cronograma tentativo PLN 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 3160
    },
    {
      "id": "pln-openfing-20",
      "week": "2026-10-26",
      "periodLabel": "Semana 10 · 27/10",
      "eventDate": "2026-10-27",
      "subject": "pln",
      "type": "course-class",
      "title": "Recuperación y Extracción de Información",
      "details": "Clase presencial · tema del cronograma tentativo 2026",
      "source": "Cronograma tentativo PLN 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 3170
    },
    {
      "id": "pln-no-openfing-narrativa-interactiva",
      "week": "2026-11-02",
      "periodLabel": "Semana 11 · 03/11",
      "eventDate": "2026-11-03",
      "subject": "pln",
      "type": "course-class",
      "title": "Narrativa interactiva",
      "details": "Clase presencial · tema del cronograma tentativo 2026",
      "source": "Cronograma tentativo PLN 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 3180
    },
    {
      "id": "pln-openfing-16",
      "week": "2026-11-09",
      "periodLabel": "Semana 12 · 10/11",
      "eventDate": "2026-11-10",
      "subject": "pln",
      "type": "course-class",
      "title": "Traducción automática · Tópicos · Clustering · Análisis de Sentimiento",
      "details": "Clase presencial · tema del cronograma tentativo 2026",
      "source": "Cronograma tentativo PLN 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 3190
    }
  ]
};
