window.PLAN_DATA = {
  "version": "2026.08.03-2",
  "semester": {
    "title": "Plan de estudio · segundo semestre 2026",
    "start": "2026-08-03",
    "end": "2026-11-30"
  },
  "subjects": {
    "fuaa": {
      "name": "Fundamentos de Aprendizaje Automático",
      "short": "FuAA",
      "color": "#b9ff3b",
      "status": "Cronograma oficial cargado",
      "source": "FuAA 2026"
    },
    "redes": {
      "name": "Redes de Computadoras",
      "short": "Redes",
      "color": "#31a8ff",
      "status": "Cronograma oficial cargado",
      "source": "Cronograma Redes 2026"
    },
    "fbd": {
      "name": "Fundamentos de Bases de Datos",
      "short": "FBD",
      "color": "#ff9f1c",
      "status": "Temario OpenFing cargado; fechas pendientes",
      "source": "Lista OpenFing proporcionada"
    },
    "pln": {
      "name": "Introducción al Procesamiento de Lenguaje Natural",
      "short": "IntroPLN",
      "color": "#ff4fd8",
      "status": "Cronograma y materiales pendientes",
      "source": "Pendiente"
    }
  },
  "syllabus": {
    "fuaa": [
      {
        "id": "fuaa-topic-01",
        "order": 1,
        "title": "Introducción al problema de aprendizaje",
        "details": "Video OpenFing 1 · Libro: 1.1, 1.2",
        "video": 1,
        "chapter": "1.1, 1.2"
      },
      {
        "id": "fuaa-topic-02",
        "order": 2,
        "title": "El problema de aprendizaje",
        "details": "Video OpenFing 2 · Libro: 1.3",
        "video": 2,
        "chapter": "1.3"
      },
      {
        "id": "fuaa-topic-03",
        "order": 3,
        "title": "El modelo lineal",
        "details": "Video OpenFing 4 · Libro: 3.1, 3.2, 3.4",
        "video": 4,
        "chapter": "3.1, 3.2, 3.4"
      },
      {
        "id": "fuaa-topic-04",
        "order": 4,
        "title": "Error y ruido",
        "details": "Video OpenFing 5 · Libro: 1.4, 1.3.3",
        "video": 5,
        "chapter": "1.4, 1.3.3"
      },
      {
        "id": "fuaa-topic-05",
        "order": 5,
        "title": "Entrenamiento versus prueba",
        "details": "Video OpenFing 6 · Libro: 2.1, 2.1.1",
        "video": 6,
        "chapter": "2.1, 2.1.1"
      },
      {
        "id": "fuaa-topic-06",
        "order": 6,
        "title": "Teoría de la generalización",
        "details": "Video OpenFing 8 · Libro: 2.1",
        "video": 8,
        "chapter": "2.1"
      },
      {
        "id": "fuaa-topic-07",
        "order": 7,
        "title": "La dimensión VC",
        "details": "Video OpenFing 9 · Libro: 2.2",
        "video": 9,
        "chapter": "2.2"
      },
      {
        "id": "fuaa-topic-08",
        "order": 8,
        "title": "Compromiso sesgo-varianza",
        "details": "Video OpenFing 10 · Libro: 2.3",
        "video": 10,
        "chapter": "2.3"
      },
      {
        "id": "fuaa-topic-09",
        "order": 9,
        "title": "El modelo lineal II",
        "details": "Video OpenFing 12 · Libro: 3.3",
        "video": 12,
        "chapter": "3.3"
      },
      {
        "id": "fuaa-topic-10",
        "order": 10,
        "title": "Sobreajuste",
        "details": "Video OpenFing 13 · Libro: 4.1",
        "video": 13,
        "chapter": "4.1"
      },
      {
        "id": "fuaa-topic-11",
        "order": 11,
        "title": "Regularización",
        "details": "Video OpenFing 14 · Libro: 4.2",
        "video": 14,
        "chapter": "4.2"
      },
      {
        "id": "fuaa-topic-12",
        "order": 12,
        "title": "Validación",
        "details": "Video OpenFing 16 · Libro: 4.3",
        "video": 16,
        "chapter": "4.3"
      },
      {
        "id": "fuaa-topic-13",
        "order": 13,
        "title": "Epílogo de los fundamentos teóricos",
        "details": "Video OpenFing 17 · Libro: 5.1, 5.2, 5.3",
        "video": 17,
        "chapter": "5.1, 5.2, 5.3"
      },
      {
        "id": "fuaa-topic-14",
        "order": 14,
        "title": "Perceptrón multicapa",
        "details": "Video OpenFing 18 · Libro: 7.1, 7.2",
        "video": 18,
        "chapter": "7.1, 7.2"
      },
      {
        "id": "fuaa-topic-15",
        "order": 15,
        "title": "Redes neuronales",
        "details": "Video OpenFing 19 · Libro: 7.3, 7.4, 7.5, 7.6",
        "video": 19,
        "chapter": "7.3, 7.4, 7.5, 7.6"
      },
      {
        "id": "fuaa-topic-16",
        "order": 16,
        "title": "Máquinas de vectores de soporte",
        "details": "Video OpenFing 22 · Libro: 8.1, 8.2",
        "video": 22,
        "chapter": "8.1, 8.2"
      },
      {
        "id": "fuaa-topic-17",
        "order": 17,
        "title": "Métodos de Kernel",
        "details": "Video OpenFing 23 · Libro: 8.3, 8.4",
        "video": 23,
        "chapter": "8.3, 8.4"
      },
      {
        "id": "fuaa-topic-18",
        "order": 18,
        "title": "Métodos basados en similitud",
        "details": "Video OpenFing 25 · Libro: 6.1, 6.2, 6.3",
        "video": 25,
        "chapter": "6.1, 6.2, 6.3"
      },
      {
        "id": "fuaa-topic-19",
        "order": 19,
        "title": "Aprendizaje no supervisado",
        "details": "Video OpenFing 26 · Libro: 6.3, 6.4",
        "video": 26,
        "chapter": "6.3, 6.4"
      },
      {
        "id": "fuaa-topic-20",
        "order": 20,
        "title": "Ingeniería de características",
        "details": "Video OpenFing 28",
        "video": 28,
        "chapter": ""
      }
    ],
    "redes": [
      {
        "id": "redes-unit-01",
        "order": 1,
        "title": "Presentación e introducción",
        "details": "Capítulo 1 · Clases OpenFing 1, 2 y 3"
      },
      {
        "id": "redes-unit-02",
        "order": 2,
        "title": "Capa de aplicación",
        "details": "Capítulo 2 · Clases OpenFing 4 a 7"
      },
      {
        "id": "redes-unit-03",
        "order": 3,
        "title": "Capa de transporte",
        "details": "Capítulo 3 · Clases OpenFing 8 a 11"
      },
      {
        "id": "redes-unit-04",
        "order": 4,
        "title": "Red: plano de datos",
        "details": "Capítulo 4 hasta 4.3 · Clases OpenFing 12 y 13"
      },
      {
        "id": "redes-unit-05",
        "order": 5,
        "title": "IPv6",
        "details": "Material IPv6 · Clases OpenFing 14, 18 y 19"
      },
      {
        "id": "redes-unit-06",
        "order": 6,
        "title": "Red: plano de control",
        "details": "Capítulo 5 · Clases OpenFing 14 a 17 · Multicast y broadcast"
      },
      {
        "id": "redes-unit-07",
        "order": 7,
        "title": "Capa de enlace",
        "details": "Capítulo 6 · Clases OpenFing 20 a 23"
      }
    ],
    "fbd": [
      {
        "id": "fbd-topic-01",
        "order": 1,
        "title": "Presentación del curso. Introducción y conceptos generales",
        "details": "Clase OpenFing 1 · Sin fecha oficial"
      },
      {
        "id": "fbd-topic-02",
        "order": 2,
        "title": "Diseño conceptual",
        "details": "Clase OpenFing 2 · Sin fecha oficial"
      },
      {
        "id": "fbd-topic-03",
        "order": 3,
        "title": "Diseño conceptual. Ejemplo",
        "details": "Clase OpenFing 3 · Sin fecha oficial"
      },
      {
        "id": "fbd-topic-04",
        "order": 4,
        "title": "Diseño conceptual. Modelo relacional",
        "details": "Clase OpenFing 4 · Sin fecha oficial"
      },
      {
        "id": "fbd-topic-05",
        "order": 5,
        "title": "Álgebra relacional",
        "details": "Clase OpenFing 5 · Sin fecha oficial"
      },
      {
        "id": "fbd-topic-06",
        "order": 6,
        "title": "Álgebra relacional. Ejemplos",
        "details": "Clase OpenFing 6 · Sin fecha oficial"
      },
      {
        "id": "fbd-topic-07",
        "order": 7,
        "title": "Cálculo Relacional",
        "details": "Clase OpenFing 7 · Sin fecha oficial"
      },
      {
        "id": "fbd-topic-08",
        "order": 8,
        "title": "Cálculo Relacional. Ejemplos",
        "details": "Clase OpenFing 8 · Sin fecha oficial"
      },
      {
        "id": "fbd-topic-09",
        "order": 9,
        "title": "Lenguajes de Consulta - SQL",
        "details": "Clase OpenFing 9 · Sin fecha oficial"
      },
      {
        "id": "fbd-topic-10",
        "order": 10,
        "title": "Práctico de SQL",
        "details": "Clase OpenFing 10 · Sin fecha oficial"
      },
      {
        "id": "fbd-topic-11",
        "order": 11,
        "title": "Diseño relacional. Dependencias funcionales - 1",
        "details": "Clase OpenFing 11 · Sin fecha oficial"
      },
      {
        "id": "fbd-topic-12",
        "order": 12,
        "title": "Diseño relacional. Dependencias funcionales - 2",
        "details": "Clase OpenFing 12 · Sin fecha oficial"
      },
      {
        "id": "fbd-topic-13",
        "order": 13,
        "title": "Normalización - 1",
        "details": "Clase OpenFing 13 · Sin fecha oficial"
      },
      {
        "id": "fbd-topic-14",
        "order": 14,
        "title": "Normalización - 2",
        "details": "Clase OpenFing 14 · Sin fecha oficial"
      },
      {
        "id": "fbd-topic-15",
        "order": 15,
        "title": "Dependencias Multivaluadas",
        "details": "Clase OpenFing 15 · Sin fecha oficial"
      },
      {
        "id": "fbd-topic-16",
        "order": 16,
        "title": "Pasaje de MER a MR",
        "details": "Clase OpenFing 16 · Sin fecha oficial"
      },
      {
        "id": "fbd-topic-17",
        "order": 17,
        "title": "Ejercicios MER-MR y Estrategias BDMS",
        "details": "Clase OpenFing 17 · Sin fecha oficial"
      },
      {
        "id": "fbd-topic-18",
        "order": 18,
        "title": "Procesamiento y Optimización de Consultas",
        "details": "Clase OpenFing 18 · Sin fecha oficial"
      },
      {
        "id": "fbd-topic-19",
        "order": 19,
        "title": "Optimización de Consultas",
        "details": "Clase OpenFing 19 · Sin fecha oficial"
      },
      {
        "id": "fbd-topic-20",
        "order": 20,
        "title": "Transacciones y Concurrencia",
        "details": "Clase OpenFing 20 · Sin fecha oficial"
      },
      {
        "id": "fbd-topic-21",
        "order": 21,
        "title": "Concurrencia y Recuperación",
        "details": "Clase OpenFing 21 · Sin fecha oficial"
      }
    ],
    "pln": [
      {
        "id": "pln-pending",
        "order": 1,
        "title": "Cronograma pendiente",
        "details": "Agregar clases, temario, trabajos y fechas cuando el curso los publique."
      }
    ]
  },
  "items": [
    {
      "id": "fuaa-event-001",
      "date": "2026-08-03",
      "subject": "fuaa",
      "type": "class",
      "title": "Presentación",
      "details": "Tema 1",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-study-01",
      "date": "2026-08-03",
      "subject": "redes",
      "type": "study",
      "title": "Semana 1: Presentación e introducción",
      "details": "Cap. 1 · Clases 1, 2 y 3. Práctico: P1 - Retardos.",
      "minutes": 210,
      "fixed": false,
      "source": "Sugerencia basada en Cronograma Redes 2026",
      "priority": "high"
    },
    {
      "id": "fuaa-prep-01",
      "date": "2026-08-04",
      "subject": "fuaa",
      "type": "study",
      "title": "Preparar temas 1, 2",
      "details": "1. Introducción al problema de aprendizaje; 2. El problema de aprendizaje. T1: video 1, libro 1.1, 1.2 · T2: video 2, libro 1.3.",
      "minutes": 180,
      "fixed": false,
      "source": "Sugerencia basada en el cronograma FuAA",
      "priority": "high"
    },
    {
      "id": "redes-event-01-tu",
      "date": "2026-08-04",
      "subject": "redes",
      "type": "class",
      "title": "Presentación del curso y repaso de introducción",
      "details": "Clase del martes · Semana 1",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-event-002",
      "date": "2026-08-05",
      "subject": "fuaa",
      "type": "workshop",
      "title": "Consultas / Taller",
      "details": "P0, Python y NumPy",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-event-01-th",
      "date": "2026-08-06",
      "subject": "redes",
      "type": "class",
      "title": "Práctico 1",
      "details": "Clase del jueves · Semana 1",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "redes-ob1-publish",
      "date": "2026-08-07",
      "subject": "redes",
      "type": "assignment-published",
      "title": "Se publica Obligatorio 1",
      "details": "Plazo previsto: 5 semanas",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "high"
    },
    {
      "id": "redes-ob-milestone-01",
      "date": "2026-08-09",
      "subject": "redes",
      "type": "assignment",
      "title": "Ob1: leer letra y dividir tareas",
      "details": "Definir alcance, integrantes y primera lista de pendientes",
      "minutes": 90,
      "fixed": false,
      "source": "Sugerencia de trabajo",
      "priority": "high"
    },
    {
      "id": "fuaa-event-003",
      "date": "2026-08-10",
      "subject": "fuaa",
      "type": "discussion",
      "title": "Discusión 1 y 2",
      "details": "Temas 1 y 2",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-study-02",
      "date": "2026-08-10",
      "subject": "redes",
      "type": "study",
      "title": "Semana 2: Aplicación",
      "details": "Cap. 2 hasta 2.3 + 2.7 · Clases 4 y 5. Práctico: P1 y P2 - HTTP.",
      "minutes": 210,
      "fixed": false,
      "source": "Sugerencia basada en Cronograma Redes 2026",
      "priority": "high"
    },
    {
      "id": "fuaa-review-01",
      "date": "2026-08-11",
      "subject": "fuaa",
      "type": "review",
      "title": "Repaso para Control 0",
      "details": "Temas 1 y 2",
      "minutes": 75,
      "fixed": false,
      "source": "Sugerencia basada en evaluaciones FuAA",
      "priority": "high"
    },
    {
      "id": "redes-event-02-tu",
      "date": "2026-08-11",
      "subject": "redes",
      "type": "class",
      "title": "Repaso HTTP y Práctico 2",
      "details": "Clase del martes · Semana 2",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-event-004",
      "date": "2026-08-12",
      "subject": "fuaa",
      "type": "control",
      "title": "Control 0",
      "details": "Temas 1 y 2",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "critical"
    },
    {
      "id": "fuaa-event-005",
      "date": "2026-08-12",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 1",
      "details": "Temas 1 y 2",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-event-006",
      "date": "2026-08-12",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP01",
      "details": "Vinculado al Práctico 1",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-event-02-we",
      "date": "2026-08-12",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "Semana 2",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "redes-event-02-th",
      "date": "2026-08-13",
      "subject": "redes",
      "type": "class",
      "title": "Repaso sockets y Práctico 3",
      "details": "Clase del jueves · Semana 2",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-prep-02",
      "date": "2026-08-16",
      "subject": "fuaa",
      "type": "study",
      "title": "Preparar temas 3, 4",
      "details": "3. El modelo lineal; 4. Error y ruido. T3: video 4, libro 3.1, 3.2, 3.4 · T4: video 5, libro 1.4, 1.3.3.",
      "minutes": 180,
      "fixed": false,
      "source": "Sugerencia basada en el cronograma FuAA",
      "priority": "high"
    },
    {
      "id": "fuaa-event-007",
      "date": "2026-08-17",
      "subject": "fuaa",
      "type": "discussion",
      "title": "Discusión 3 y 4",
      "details": "Temas 3 y 4",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-study-03",
      "date": "2026-08-17",
      "subject": "redes",
      "type": "study",
      "title": "Semana 3: Aplicación",
      "details": "Cap. 2 hasta el final · Clases 6 y 7. Práctico: P3 - Sockets.",
      "minutes": 210,
      "fixed": false,
      "source": "Sugerencia basada en Cronograma Redes 2026",
      "priority": "high"
    },
    {
      "id": "fuaa-review-02",
      "date": "2026-08-18",
      "subject": "fuaa",
      "type": "review",
      "title": "Repaso para Control 1",
      "details": "Temas 1, 2 y 3",
      "minutes": 90,
      "fixed": false,
      "source": "Sugerencia basada en evaluaciones FuAA",
      "priority": "high"
    },
    {
      "id": "redes-event-03-tu",
      "date": "2026-08-18",
      "subject": "redes",
      "type": "class",
      "title": "Práctico 3",
      "details": "Clase del martes · Semana 3",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-event-008",
      "date": "2026-08-19",
      "subject": "fuaa",
      "type": "control",
      "title": "Control 1",
      "details": "Temas 1, 2 y 3",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "critical"
    },
    {
      "id": "fuaa-event-009",
      "date": "2026-08-19",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 2",
      "details": "Temas 3, 4 y 5",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-event-010",
      "date": "2026-08-19",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP02",
      "details": "Vinculado al Práctico 2",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-event-03-we",
      "date": "2026-08-19",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "Semana 3",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "redes-event-03-th",
      "date": "2026-08-20",
      "subject": "redes",
      "type": "class",
      "title": "Práctico 3",
      "details": "Clase del jueves · Semana 3",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-prep-03",
      "date": "2026-08-23",
      "subject": "fuaa",
      "type": "study",
      "title": "Preparar temas 5, 6",
      "details": "5. Entrenamiento versus prueba; 6. Teoría de la generalización. T5: video 6, libro 2.1, 2.1.1 · T6: video 8, libro 2.1.",
      "minutes": 180,
      "fixed": false,
      "source": "Sugerencia basada en el cronograma FuAA",
      "priority": "high"
    },
    {
      "id": "redes-ob-milestone-02",
      "date": "2026-08-23",
      "subject": "redes",
      "type": "assignment",
      "title": "Ob1: primer avance funcional",
      "details": "Tener una parte ejecutable y dudas concretas para monitoreo",
      "minutes": 180,
      "fixed": false,
      "source": "Sugerencia de trabajo",
      "priority": "high"
    },
    {
      "id": "fuaa-event-011",
      "date": "2026-08-24",
      "subject": "fuaa",
      "type": "discussion",
      "title": "Discusión 5 y 6",
      "details": "Temas 5 y 6",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-study-04",
      "date": "2026-08-24",
      "subject": "redes",
      "type": "study",
      "title": "Semana 4: Aplicación",
      "details": "Cap. 2 hasta el final · Clases 6 y 7. Práctico: P3 y P4 - EMAIL y DNS.",
      "minutes": 210,
      "fixed": false,
      "source": "Sugerencia basada en Cronograma Redes 2026",
      "priority": "high"
    },
    {
      "id": "redes-event-04-tu",
      "date": "2026-08-25",
      "subject": "redes",
      "type": "holiday",
      "title": "Feriado",
      "details": "Clase del martes · Semana 4",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-event-012",
      "date": "2026-08-26",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 2",
      "details": "Temas 3, 4 y 5",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-event-013",
      "date": "2026-08-26",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP03",
      "details": "Vinculado al Práctico 2",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-event-04-we",
      "date": "2026-08-26",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "Semana 4",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "redes-event-04-th",
      "date": "2026-08-27",
      "subject": "redes",
      "type": "class",
      "title": "Repaso DNS y Práctico 4",
      "details": "Clase del jueves · Semana 4",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-prep-04",
      "date": "2026-08-30",
      "subject": "fuaa",
      "type": "study",
      "title": "Preparar temas 7, 8",
      "details": "7. La dimensión VC; 8. Compromiso sesgo-varianza. T7: video 9, libro 2.2 · T8: video 10, libro 2.3.",
      "minutes": 180,
      "fixed": false,
      "source": "Sugerencia basada en el cronograma FuAA",
      "priority": "high"
    },
    {
      "id": "fuaa-event-014",
      "date": "2026-08-31",
      "subject": "fuaa",
      "type": "discussion",
      "title": "Discusión 7 y 8",
      "details": "Temas 7 y 8",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-study-05",
      "date": "2026-08-31",
      "subject": "redes",
      "type": "study",
      "title": "Semana 5: Transporte",
      "details": "Cap. 3 hasta 3.4 · Clases 8 y 9. Práctico: P4.",
      "minutes": 210,
      "fixed": false,
      "source": "Sugerencia basada en Cronograma Redes 2026",
      "priority": "high"
    },
    {
      "id": "fuaa-review-03",
      "date": "2026-09-01",
      "subject": "fuaa",
      "type": "review",
      "title": "Repaso para Control 2",
      "details": "Temas 4, 5, 6 y 7",
      "minutes": 120,
      "fixed": false,
      "source": "Sugerencia basada en evaluaciones FuAA",
      "priority": "high"
    },
    {
      "id": "redes-event-05-tu",
      "date": "2026-09-01",
      "subject": "redes",
      "type": "class",
      "title": "Repaso EMAIL y Práctico 4",
      "details": "Clase del martes · Semana 5",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-event-015",
      "date": "2026-09-02",
      "subject": "fuaa",
      "type": "control",
      "title": "Control 2",
      "details": "Temas 4, 5, 6 y 7",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "critical"
    },
    {
      "id": "fuaa-event-016",
      "date": "2026-09-02",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 3",
      "details": "Temas 6, 7, 8 y 9",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-event-017",
      "date": "2026-09-02",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP04",
      "details": "Vinculado al Práctico 3",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-event-05-we",
      "date": "2026-09-02",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "Semana 5",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "redes-event-05-th",
      "date": "2026-09-03",
      "subject": "redes",
      "type": "class",
      "title": "Repaso transporte y RDT",
      "details": "Clase del jueves · Semana 5",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-prep-05",
      "date": "2026-09-06",
      "subject": "fuaa",
      "type": "study",
      "title": "Preparar temas 9, 10, 11",
      "details": "9. El modelo lineal II; 10. Sobreajuste; 11. Regularización. T9: video 12, libro 3.3 · T10: video 13, libro 4.1 · T11: video 14, libro 4.2.",
      "minutes": 240,
      "fixed": false,
      "source": "Sugerencia basada en el cronograma FuAA",
      "priority": "high"
    },
    {
      "id": "redes-ob-milestone-03",
      "date": "2026-09-06",
      "subject": "redes",
      "type": "assignment",
      "title": "Ob1: integración y pruebas",
      "details": "Cerrar funcionalidad principal antes de la semana de entrega",
      "minutes": 240,
      "fixed": false,
      "source": "Sugerencia de trabajo",
      "priority": "high"
    },
    {
      "id": "fuaa-event-018",
      "date": "2026-09-07",
      "subject": "fuaa",
      "type": "discussion",
      "title": "Discusión 9, 10 y 11",
      "details": "Temas 9, 10 y 11",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-study-06",
      "date": "2026-09-07",
      "subject": "redes",
      "type": "study",
      "title": "Semana 6: Transporte",
      "details": "Cap. 3 hasta 3.4 · Clases 8 y 9. Práctico: P5 - RDT, control de congestión y TCP.",
      "minutes": 210,
      "fixed": false,
      "source": "Sugerencia basada en Cronograma Redes 2026",
      "priority": "high"
    },
    {
      "id": "fuaa-event-019",
      "date": "2026-09-09",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 3 / Práctico 4",
      "details": "Temas 6, 7, 8 y 9",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-event-020",
      "date": "2026-09-09",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP05",
      "details": "Vinculado a Prácticos 3 y 4",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-event-06-we",
      "date": "2026-09-09",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "Semana 6",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "redes-event-06-th",
      "date": "2026-09-10",
      "subject": "redes",
      "type": "class",
      "title": "P5",
      "details": "Clase del jueves · Semana 6",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "redes-ob-milestone-04",
      "date": "2026-09-10",
      "subject": "redes",
      "type": "assignment",
      "title": "Ob1: revisión final",
      "details": "Pruebas, formato de entrega y respaldo",
      "minutes": 150,
      "fixed": false,
      "source": "Sugerencia de trabajo",
      "priority": "high"
    },
    {
      "id": "redes-ob1-due",
      "date": "2026-09-11",
      "subject": "redes",
      "type": "deadline",
      "title": "Entrega del Obligatorio 1",
      "details": "Fecha de entrega del cronograma",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "critical"
    },
    {
      "id": "fuaa-prep-06",
      "date": "2026-09-13",
      "subject": "fuaa",
      "type": "study",
      "title": "Preparar temas 12",
      "details": "12. Validación. T12: video 16, libro 4.3.",
      "minutes": 120,
      "fixed": false,
      "source": "Sugerencia basada en el cronograma FuAA",
      "priority": "high"
    },
    {
      "id": "fuaa-event-021",
      "date": "2026-09-14",
      "subject": "fuaa",
      "type": "discussion",
      "title": "Discusión / Práctico 4",
      "details": "Tema 12",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-study-07",
      "date": "2026-09-14",
      "subject": "redes",
      "type": "study",
      "title": "Semana 7: Transporte",
      "details": "Cap. 3 hasta 3.6 · Clases 10 y 11. Práctico: P5.",
      "minutes": 210,
      "fixed": false,
      "source": "Sugerencia basada en Cronograma Redes 2026",
      "priority": "high"
    },
    {
      "id": "fuaa-review-04",
      "date": "2026-09-15",
      "subject": "fuaa",
      "type": "review",
      "title": "Repaso para Control 3",
      "details": "Temas 8, 9, 10 y 11",
      "minutes": 120,
      "fixed": false,
      "source": "Sugerencia basada en evaluaciones FuAA",
      "priority": "high"
    },
    {
      "id": "redes-event-07-tu",
      "date": "2026-09-15",
      "subject": "redes",
      "type": "class",
      "title": "P5",
      "details": "Clase del martes · Semana 7",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-event-022",
      "date": "2026-09-16",
      "subject": "fuaa",
      "type": "control",
      "title": "Control 3",
      "details": "Temas 8, 9, 10 y 11",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "critical"
    },
    {
      "id": "fuaa-event-023",
      "date": "2026-09-16",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 4",
      "details": "Temas 10, 11 y 12",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-event-024",
      "date": "2026-09-16",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP06",
      "details": "Vinculado al Práctico 4",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-event-07-we",
      "date": "2026-09-16",
      "subject": "redes",
      "type": "defense",
      "title": "Defensas",
      "details": "Semana 7",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "critical"
    },
    {
      "id": "redes-event-07-th",
      "date": "2026-09-17",
      "subject": "redes",
      "type": "class",
      "title": "Repaso TCP y control de congestión",
      "details": "Clase del jueves · Semana 7",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-review-05",
      "date": "2026-09-20",
      "subject": "fuaa",
      "type": "review",
      "title": "Repaso final para primer parcial",
      "details": "Temas 1 a 12 y prácticos 1 a 4",
      "minutes": 240,
      "fixed": false,
      "source": "Sugerencia basada en evaluaciones FuAA",
      "priority": "high"
    },
    {
      "id": "fuaa-event-025",
      "date": "2026-09-21",
      "subject": "fuaa",
      "type": "review",
      "title": "Consultas / Taller para parciales",
      "details": "Semana de parciales",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-event-08-partial",
      "date": "2026-09-21",
      "subject": "redes",
      "type": "partial-window",
      "title": "Período de parciales",
      "details": "Semana 8 del cronograma",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "critical"
    },
    {
      "id": "redes-study-08",
      "date": "2026-09-21",
      "subject": "redes",
      "type": "review",
      "title": "Semana de parciales de Redes",
      "details": "Semana de parciales",
      "minutes": 240,
      "fixed": false,
      "source": "Sugerencia basada en Cronograma Redes 2026",
      "priority": "high"
    },
    {
      "id": "fuaa-event-026",
      "date": "2026-09-23",
      "subject": "fuaa",
      "type": "partial",
      "title": "Primer parcial",
      "details": "Fecha principal indicada en el cronograma",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "critical"
    },
    {
      "id": "fuaa-event-027",
      "date": "2026-09-28",
      "subject": "fuaa",
      "type": "partial-window",
      "title": "Período de parciales",
      "details": "Semana de parciales",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-event-09-partial",
      "date": "2026-09-28",
      "subject": "redes",
      "type": "partial-window",
      "title": "Período de parciales",
      "details": "Semana 9 del cronograma",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "critical"
    },
    {
      "id": "redes-study-09",
      "date": "2026-09-28",
      "subject": "redes",
      "type": "review",
      "title": "Semana de parciales de Redes",
      "details": "Semana de parciales",
      "minutes": 240,
      "fixed": false,
      "source": "Sugerencia basada en Cronograma Redes 2026",
      "priority": "high"
    },
    {
      "id": "fuaa-event-028",
      "date": "2026-09-30",
      "subject": "fuaa",
      "type": "partial-window",
      "title": "Período de parciales",
      "details": "Semana de parciales",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-event-09-th",
      "date": "2026-10-01",
      "subject": "redes",
      "type": "no-class",
      "title": "No hay clase",
      "details": "Clase del jueves · Semana 9",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "redes-ob2-publish",
      "date": "2026-10-02",
      "subject": "redes",
      "type": "assignment-published",
      "title": "Se publica Obligatorio 2",
      "details": "Plazo previsto: 6 semanas",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "high"
    },
    {
      "id": "fuaa-prep-07",
      "date": "2026-10-04",
      "subject": "fuaa",
      "type": "study",
      "title": "Preparar temas 13, 14, 15",
      "details": "13. Epílogo de los fundamentos teóricos; 14. Perceptrón multicapa; 15. Redes neuronales. T13: video 17, libro 5.1, 5.2, 5.3 · T14: video 18, libro 7.1, 7.2 · T15: video 19, libro 7.3, 7.4, 7.5, 7.6.",
      "minutes": 240,
      "fixed": false,
      "source": "Sugerencia basada en el cronograma FuAA",
      "priority": "high"
    },
    {
      "id": "redes-ob-milestone-05",
      "date": "2026-10-04",
      "subject": "redes",
      "type": "assignment",
      "title": "Ob2: leer letra y dividir tareas",
      "details": "Definir alcance, integrantes y primera lista de pendientes",
      "minutes": 90,
      "fixed": false,
      "source": "Sugerencia de trabajo",
      "priority": "high"
    },
    {
      "id": "fuaa-event-029",
      "date": "2026-10-05",
      "subject": "fuaa",
      "type": "discussion",
      "title": "Discusión 13, 14 y 15",
      "details": "Temas 13, 14 y 15",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-study-10",
      "date": "2026-10-05",
      "subject": "redes",
      "type": "study",
      "title": "Semana 10: Transporte",
      "details": "Cap. 3 hasta el final · Clase 11. Práctico: P5 - RDT, control de congestión y TCP.",
      "minutes": 210,
      "fixed": false,
      "source": "Sugerencia basada en Cronograma Redes 2026",
      "priority": "high"
    },
    {
      "id": "redes-event-10-tu",
      "date": "2026-10-06",
      "subject": "redes",
      "type": "class",
      "title": "Repaso control de congestión y P5",
      "details": "Clase del martes · Semana 10",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-event-030",
      "date": "2026-10-07",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 5 / scikit-learn",
      "details": "Temas 14 y 15",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-event-031",
      "date": "2026-10-07",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP07",
      "details": "Vinculado al Práctico 5",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-event-10-we",
      "date": "2026-10-07",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "Semana 10",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "redes-event-10-th",
      "date": "2026-10-08",
      "subject": "redes",
      "type": "class",
      "title": "P5",
      "details": "Clase del jueves · Semana 10",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-event-032",
      "date": "2026-10-12",
      "subject": "fuaa",
      "type": "holiday",
      "title": "Feriado",
      "details": "Sin actividad presencial",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-study-11",
      "date": "2026-10-12",
      "subject": "redes",
      "type": "study",
      "title": "Semana 11: Red: plano de datos",
      "details": "Cap. 4 hasta 4.3 · Clases 12 y 13. Práctico: P6 - Direccionamiento, numeración, forwarding y LPM.",
      "minutes": 210,
      "fixed": false,
      "source": "Sugerencia basada en Cronograma Redes 2026",
      "priority": "high"
    },
    {
      "id": "redes-event-11-tu",
      "date": "2026-10-13",
      "subject": "redes",
      "type": "class",
      "title": "Repaso servicios, planos, políticas y P6",
      "details": "Clase del martes · Semana 11",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-event-033",
      "date": "2026-10-14",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 5",
      "details": "Temas 14 y 15",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-event-034",
      "date": "2026-10-14",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP08",
      "details": "Vinculado al Práctico 5",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-event-11-we",
      "date": "2026-10-14",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "Semana 11",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "redes-event-11-th",
      "date": "2026-10-15",
      "subject": "redes",
      "type": "class",
      "title": "Repaso numeración IP y P6",
      "details": "Clase del jueves · Semana 11",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-prep-08",
      "date": "2026-10-18",
      "subject": "fuaa",
      "type": "study",
      "title": "Preparar temas 16, 17",
      "details": "16. Máquinas de vectores de soporte; 17. Métodos de Kernel. T16: video 22, libro 8.1, 8.2 · T17: video 23, libro 8.3, 8.4.",
      "minutes": 180,
      "fixed": false,
      "source": "Sugerencia basada en el cronograma FuAA",
      "priority": "high"
    },
    {
      "id": "redes-ob-milestone-06",
      "date": "2026-10-18",
      "subject": "redes",
      "type": "assignment",
      "title": "Ob2: primer avance funcional",
      "details": "Tener una parte ejecutable y dudas concretas para monitoreo",
      "minutes": 180,
      "fixed": false,
      "source": "Sugerencia de trabajo",
      "priority": "high"
    },
    {
      "id": "fuaa-event-035",
      "date": "2026-10-19",
      "subject": "fuaa",
      "type": "discussion",
      "title": "Discusión 16 y 17",
      "details": "Temas 16 y 17",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-study-12",
      "date": "2026-10-19",
      "subject": "redes",
      "type": "study",
      "title": "Semana 12: IPv6",
      "details": "Material IPv6 · Clases 14, 18 y 19. Práctico: P6.",
      "minutes": 210,
      "fixed": false,
      "source": "Sugerencia basada en Cronograma Redes 2026",
      "priority": "high"
    },
    {
      "id": "fuaa-review-06",
      "date": "2026-10-20",
      "subject": "fuaa",
      "type": "review",
      "title": "Repaso para Control 4",
      "details": "Temas 14 y 15",
      "minutes": 90,
      "fixed": false,
      "source": "Sugerencia basada en evaluaciones FuAA",
      "priority": "high"
    },
    {
      "id": "redes-event-12-tu",
      "date": "2026-10-20",
      "subject": "redes",
      "type": "class",
      "title": "Práctico 6",
      "details": "Clase del martes · Semana 12",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-event-036",
      "date": "2026-10-21",
      "subject": "fuaa",
      "type": "control",
      "title": "Control 4",
      "details": "Temas 14 y 15",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "critical"
    },
    {
      "id": "fuaa-event-037",
      "date": "2026-10-21",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 6",
      "details": "Temas 16 y 17",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-event-038",
      "date": "2026-10-21",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP09",
      "details": "Vinculado al Práctico 6",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-event-12-we",
      "date": "2026-10-21",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "Semana 12",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "redes-event-12-th",
      "date": "2026-10-22",
      "subject": "redes",
      "type": "class",
      "title": "Práctico 6",
      "details": "Clase del jueves · Semana 12",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-prep-09",
      "date": "2026-10-25",
      "subject": "fuaa",
      "type": "study",
      "title": "Preparar temas 18, 19",
      "details": "18. Métodos basados en similitud; 19. Aprendizaje no supervisado. T18: video 25, libro 6.1, 6.2, 6.3 · T19: video 26, libro 6.3, 6.4.",
      "minutes": 180,
      "fixed": false,
      "source": "Sugerencia basada en el cronograma FuAA",
      "priority": "high"
    },
    {
      "id": "fuaa-event-039",
      "date": "2026-10-26",
      "subject": "fuaa",
      "type": "discussion",
      "title": "Discusión 18 y 19",
      "details": "Temas 18 y 19",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-study-13",
      "date": "2026-10-26",
      "subject": "redes",
      "type": "study",
      "title": "Semana 13: Red: plano de control",
      "details": "Cap. 5 hasta 5.3 · Clases 14 y 15. Práctico: P7 - Enrutamiento DV/LS, OSPF y BGP.",
      "minutes": 210,
      "fixed": false,
      "source": "Sugerencia basada en Cronograma Redes 2026",
      "priority": "high"
    },
    {
      "id": "fuaa-review-07",
      "date": "2026-10-27",
      "subject": "fuaa",
      "type": "review",
      "title": "Repaso para Control 5",
      "details": "Temas 16 y 17",
      "minutes": 90,
      "fixed": false,
      "source": "Sugerencia basada en evaluaciones FuAA",
      "priority": "high"
    },
    {
      "id": "redes-event-13-tu",
      "date": "2026-10-27",
      "subject": "redes",
      "type": "class",
      "title": "Repaso algoritmos de enrutamiento",
      "details": "Clase del martes · Semana 13",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-event-040",
      "date": "2026-10-28",
      "subject": "fuaa",
      "type": "control",
      "title": "Control 5",
      "details": "Temas 16 y 17",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "critical"
    },
    {
      "id": "fuaa-event-041",
      "date": "2026-10-28",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 6",
      "details": "Temas 16 y 17",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-event-042",
      "date": "2026-10-28",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP10",
      "details": "Vinculado al Práctico 6",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-event-13-we",
      "date": "2026-10-28",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "Semana 13",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "redes-event-13-th",
      "date": "2026-10-29",
      "subject": "redes",
      "type": "class",
      "title": "Repaso OSPF y BGP, Práctico 7",
      "details": "Clase del jueves · Semana 13",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "redes-ob-milestone-07",
      "date": "2026-11-01",
      "subject": "redes",
      "type": "assignment",
      "title": "Ob2: integración y pruebas",
      "details": "Cerrar funcionalidad principal con dos semanas de margen",
      "minutes": 240,
      "fixed": false,
      "source": "Sugerencia de trabajo",
      "priority": "high"
    },
    {
      "id": "fuaa-event-043",
      "date": "2026-11-02",
      "subject": "fuaa",
      "type": "holiday",
      "title": "Feriado",
      "details": "Sin actividad presencial",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-study-14",
      "date": "2026-11-02",
      "subject": "redes",
      "type": "study",
      "title": "Semana 14: Red: plano de control",
      "details": "Cap. 5 hasta el final + multicast y broadcast · Clases 16 y 17. Práctico: P7.",
      "minutes": 210,
      "fixed": false,
      "source": "Sugerencia basada en Cronograma Redes 2026",
      "priority": "high"
    },
    {
      "id": "fuaa-prep-10",
      "date": "2026-11-03",
      "subject": "fuaa",
      "type": "study",
      "title": "Preparar temas 20",
      "details": "20. Ingeniería de características. T20: video 28.",
      "minutes": 120,
      "fixed": false,
      "source": "Sugerencia basada en el cronograma FuAA",
      "priority": "high"
    },
    {
      "id": "redes-event-14-tu",
      "date": "2026-11-03",
      "subject": "redes",
      "type": "class",
      "title": "Práctico 7",
      "details": "Clase del martes · Semana 14",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-event-044",
      "date": "2026-11-04",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 7",
      "details": "Temas 18, 19 y 20",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-event-045",
      "date": "2026-11-04",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP11",
      "details": "Vinculado al Práctico 7",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-event-14-we",
      "date": "2026-11-04",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "Semana 14",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "redes-event-14-th",
      "date": "2026-11-05",
      "subject": "redes",
      "type": "class",
      "title": "Práctico 7",
      "details": "Clase del jueves · Semana 14",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-event-046",
      "date": "2026-11-09",
      "subject": "fuaa",
      "type": "discussion",
      "title": "Discusión 20",
      "details": "Tema 20",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-event-047",
      "date": "2026-11-09",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 7",
      "details": "Temas 18, 19 y 20",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-study-15",
      "date": "2026-11-09",
      "subject": "redes",
      "type": "study",
      "title": "Semana 15: Enlace",
      "details": "Cap. 6 hasta 6.3 · Clases 20 y 21. Práctico: P8 y P9 - Capa de enlace.",
      "minutes": 210,
      "fixed": false,
      "source": "Sugerencia basada en Cronograma Redes 2026",
      "priority": "high"
    },
    {
      "id": "fuaa-review-08",
      "date": "2026-11-10",
      "subject": "fuaa",
      "type": "review",
      "title": "Repaso para Control 6",
      "details": "Temas 18, 19 y 20",
      "minutes": 120,
      "fixed": false,
      "source": "Sugerencia basada en evaluaciones FuAA",
      "priority": "high"
    },
    {
      "id": "redes-event-15-tu",
      "date": "2026-11-10",
      "subject": "redes",
      "type": "class",
      "title": "Repaso enlace",
      "details": "Clase del martes · Semana 15",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-event-048",
      "date": "2026-11-11",
      "subject": "fuaa",
      "type": "control",
      "title": "Control 6",
      "details": "Temas 18, 19 y 20",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "critical"
    },
    {
      "id": "fuaa-event-049",
      "date": "2026-11-11",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 7",
      "details": "Temas 18, 19 y 20",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-event-050",
      "date": "2026-11-11",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP12",
      "details": "Vinculado al Práctico 7",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-event-15-we",
      "date": "2026-11-11",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "Semana 15",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "redes-event-15-th",
      "date": "2026-11-12",
      "subject": "redes",
      "type": "class",
      "title": "Práctico 8",
      "details": "Clase del jueves · Semana 15",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "redes-ob-milestone-08",
      "date": "2026-11-12",
      "subject": "redes",
      "type": "assignment",
      "title": "Ob2: revisión final",
      "details": "Pruebas, formato de entrega y respaldo",
      "minutes": 150,
      "fixed": false,
      "source": "Sugerencia de trabajo",
      "priority": "high"
    },
    {
      "id": "redes-ob2-due",
      "date": "2026-11-13",
      "subject": "redes",
      "type": "deadline",
      "title": "Entrega del Obligatorio 2",
      "details": "Fecha de entrega del cronograma",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "critical"
    },
    {
      "id": "fuaa-event-051",
      "date": "2026-11-16",
      "subject": "fuaa",
      "type": "review",
      "title": "Consultas de Ética",
      "details": "Consultas",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-study-16",
      "date": "2026-11-16",
      "subject": "redes",
      "type": "study",
      "title": "Semana 16: Enlace",
      "details": "Cap. 6 hasta el final · Clases 22 y 23. Práctico: P9.",
      "minutes": 210,
      "fixed": false,
      "source": "Sugerencia basada en Cronograma Redes 2026",
      "priority": "high"
    },
    {
      "id": "redes-event-16-tu",
      "date": "2026-11-17",
      "subject": "redes",
      "type": "class",
      "title": "Práctico 8 y Práctico 9",
      "details": "Clase del martes · Semana 16",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-event-052",
      "date": "2026-11-18",
      "subject": "fuaa",
      "type": "review",
      "title": "Consultas",
      "details": "Preparación del segundo parcial",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-event-16-we",
      "date": "2026-11-18",
      "subject": "redes",
      "type": "defense",
      "title": "Defensas",
      "details": "Semana 16",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "critical"
    },
    {
      "id": "redes-event-16-th",
      "date": "2026-11-19",
      "subject": "redes",
      "type": "class",
      "title": "Práctico 9 y cierre del curso",
      "details": "Clase del jueves · Semana 16",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "normal"
    },
    {
      "id": "fuaa-review-09",
      "date": "2026-11-22",
      "subject": "fuaa",
      "type": "review",
      "title": "Repaso final para segundo parcial",
      "details": "Temas 13 a 20 y prácticos 5 a 7",
      "minutes": 240,
      "fixed": false,
      "source": "Sugerencia basada en evaluaciones FuAA",
      "priority": "high"
    },
    {
      "id": "fuaa-event-053",
      "date": "2026-11-23",
      "subject": "fuaa",
      "type": "partial",
      "title": "Segundo parcial",
      "details": "Fecha principal indicada en el cronograma",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "critical"
    },
    {
      "id": "redes-event-17-partial",
      "date": "2026-11-23",
      "subject": "redes",
      "type": "partial-window",
      "title": "Período de parciales",
      "details": "Semana 17 del cronograma",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "critical"
    },
    {
      "id": "redes-study-17",
      "date": "2026-11-23",
      "subject": "redes",
      "type": "review",
      "title": "Semana de parciales de Redes",
      "details": "Semana de parciales",
      "minutes": 240,
      "fixed": false,
      "source": "Sugerencia basada en Cronograma Redes 2026",
      "priority": "high"
    },
    {
      "id": "fuaa-event-054",
      "date": "2026-11-25",
      "subject": "fuaa",
      "type": "partial-window",
      "title": "Período de parciales",
      "details": "Semana de parciales",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma FuAA 2026",
      "priority": "normal"
    },
    {
      "id": "redes-event-18-partial",
      "date": "2026-11-30",
      "subject": "redes",
      "type": "partial-window",
      "title": "Período de parciales",
      "details": "Semana 18 del cronograma",
      "minutes": 0,
      "fixed": true,
      "source": "Cronograma Redes 2026",
      "priority": "critical"
    },
    {
      "id": "redes-study-18",
      "date": "2026-11-30",
      "subject": "redes",
      "type": "review",
      "title": "Semana de parciales de Redes",
      "details": "Semana de parciales",
      "minutes": 240,
      "fixed": false,
      "source": "Sugerencia basada en Cronograma Redes 2026",
      "priority": "high"
    }
  ],
  "undated": [
    {
      "id": "fbd-schedule-pending",
      "subject": "fbd",
      "title": "Esperando cronograma oficial de FBD",
      "details": "El temario OpenFing ya está cargado. Falta asignar clases, prácticos, laboratorios y evaluaciones a fechas."
    },
    {
      "id": "pln-schedule-pending",
      "subject": "pln",
      "title": "Esperando cronograma oficial de IntroPLN",
      "details": "Todavía no hay clases ni temario para distribuir."
    }
  ],
  "typeLabels": {
    "study": "Estudio",
    "review": "Repaso",
    "class": "Clase",
    "workshop": "Taller",
    "discussion": "Discusión",
    "control": "Control",
    "practical": "Práctico",
    "questionnaire": "Cuestionario",
    "partial": "Parcial",
    "partial-window": "Parciales",
    "monitoring": "Monitoreo",
    "defense": "Defensa",
    "deadline": "Entrega",
    "assignment": "Obligatorio",
    "assignment-published": "Publicación",
    "holiday": "Feriado",
    "no-class": "Sin clase"
  }
};
