window.PLAN_DATA = {
  "version": "2026.08.04-3",
  "semester": {
    "title": "Cronograma · segundo semestre 2026",
    "start": "2026-08-03",
    "end": "2026-11-30"
  },
  "subjects": {
    "fuaa": {
      "name": "Fundamentos de Aprendizaje Automático",
      "short": "FuAA",
      "color": "#8cff3a",
      "status": "Cronograma oficial cargado",
      "source": "FuAA 2026"
    },
    "redes": {
      "name": "Redes de Computadoras",
      "short": "Redes",
      "color": "#36a9ff",
      "status": "Cronograma oficial cargado",
      "source": "Cronograma Redes 2026"
    },
    "fbd": {
      "name": "Fundamentos de Bases de Datos",
      "short": "FBD",
      "color": "#ff9a3c",
      "status": "Clases OpenFing cargadas; cronograma pendiente",
      "source": "Lista OpenFing proporcionada"
    },
    "pln": {
      "name": "Introducción al Procesamiento de Lenguaje Natural",
      "short": "IntroPLN",
      "color": "#ff4fcf",
      "status": "Cronograma y clases pendientes de publicación",
      "source": "Pendiente"
    }
  },
  "typeLabels": {
    "openfing": "Clase OpenFing",
    "reading": "Lectura",
    "practical": "Práctico",
    "course-class": "Actividad del curso",
    "discussion": "Discusión",
    "control": "Control",
    "questionnaire": "Cuestionario",
    "workshop": "Taller",
    "partial": "Parcial",
    "partial-window": "Período de parciales",
    "assignment-published": "Publicación de obligatorio",
    "deadline": "Entrega",
    "monitoring": "Monitoreo",
    "defense": "Defensa",
    "holiday": "Feriado",
    "no-class": "Sin clase",
    "consultation": "Consulta",
    "notice": "Pendiente"
  },
  "typeMarks": {
    "openfing": "OF",
    "reading": "LIBRO",
    "practical": "P",
    "course-class": "CLASE",
    "discussion": "DISC",
    "control": "CTRL",
    "questionnaire": "CP",
    "workshop": "TALLER",
    "partial": "PARCIAL",
    "partial-window": "PARCIALES",
    "assignment-published": "OB",
    "deadline": "ENTREGA",
    "monitoring": "LAB",
    "defense": "DEF",
    "holiday": "FERIADO",
    "no-class": "—",
    "consultation": "CONSULTA",
    "notice": "PEND."
  },
  "items": [
    {
      "id": "redes-20260803-01",
      "week": "2026-08-03",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Presentación e Introducción",
      "details": "Tema indicado para la semana",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 0
    },
    {
      "id": "redes-20260803-02",
      "week": "2026-08-03",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 1",
      "details": "Asignada dentro de Presentación e Introducción",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 10
    },
    {
      "id": "redes-20260803-03",
      "week": "2026-08-03",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 2",
      "details": "Asignada dentro de Presentación e Introducción",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 20
    },
    {
      "id": "redes-20260803-04",
      "week": "2026-08-03",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 3",
      "details": "Asignada dentro de Presentación e Introducción",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 30
    },
    {
      "id": "redes-20260803-05",
      "week": "2026-08-03",
      "eventDate": "",
      "subject": "redes",
      "type": "reading",
      "title": "Capítulo 1",
      "details": "Lectura asignada para Presentación e Introducción",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 40
    },
    {
      "id": "redes-20260803-06",
      "week": "2026-08-03",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P1 · Retardos",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 50
    },
    {
      "id": "redes-20260803-07",
      "week": "2026-08-03",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Presentación del curso y repaso de introducción",
      "details": "Actividad de clase indicada en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 60
    },
    {
      "id": "redes-20260803-08",
      "week": "2026-08-03",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Práctico 1",
      "details": "Actividad de clase indicada en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 70
    },
    {
      "id": "redes-20260803-09",
      "week": "2026-08-03",
      "eventDate": "2026-08-07",
      "subject": "redes",
      "type": "assignment-published",
      "title": "Publicación del Obligatorio 1",
      "details": "Plazo indicado: 5 semanas",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": true,
      "priority": "high",
      "order": 80
    },
    {
      "id": "redes-20260810-01",
      "week": "2026-08-10",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Aplicación",
      "details": "Tema indicado para la semana",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 90
    },
    {
      "id": "redes-20260810-02",
      "week": "2026-08-10",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 4",
      "details": "Asignada dentro de Aplicación",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 100
    },
    {
      "id": "redes-20260810-03",
      "week": "2026-08-10",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 5",
      "details": "Asignada dentro de Aplicación",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 110
    },
    {
      "id": "redes-20260810-04",
      "week": "2026-08-10",
      "eventDate": "",
      "subject": "redes",
      "type": "reading",
      "title": "Capítulo 2 hasta 2.3 y sección 2.7",
      "details": "Lectura asignada para Aplicación",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 120
    },
    {
      "id": "redes-20260810-05",
      "week": "2026-08-10",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P1 y P2 · HTTP",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 130
    },
    {
      "id": "redes-20260810-06",
      "week": "2026-08-10",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Repaso HTTP y Práctico 2",
      "details": "Actividad de clase indicada en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 140
    },
    {
      "id": "redes-20260810-07",
      "week": "2026-08-10",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Repaso sockets y Práctico 3",
      "details": "Actividad de clase indicada en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 150
    },
    {
      "id": "redes-20260810-08",
      "week": "2026-08-10",
      "eventDate": "",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 160
    },
    {
      "id": "redes-20260817-01",
      "week": "2026-08-17",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Aplicación",
      "details": "Tema indicado para la semana",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 170
    },
    {
      "id": "redes-20260817-02",
      "week": "2026-08-17",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 6",
      "details": "Asignada dentro de Aplicación",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 180
    },
    {
      "id": "redes-20260817-03",
      "week": "2026-08-17",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 7",
      "details": "Asignada dentro de Aplicación",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 190
    },
    {
      "id": "redes-20260817-04",
      "week": "2026-08-17",
      "eventDate": "",
      "subject": "redes",
      "type": "reading",
      "title": "Capítulo 2 hasta el final",
      "details": "Lectura asignada para Aplicación",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 200
    },
    {
      "id": "redes-20260817-05",
      "week": "2026-08-17",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P3 · Sockets",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 210
    },
    {
      "id": "redes-20260817-06",
      "week": "2026-08-17",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Práctico 3",
      "details": "Actividad de clase indicada en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 220
    },
    {
      "id": "redes-20260817-07",
      "week": "2026-08-17",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Práctico 3",
      "details": "Actividad de clase indicada en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 230
    },
    {
      "id": "redes-20260817-08",
      "week": "2026-08-17",
      "eventDate": "",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 240
    },
    {
      "id": "redes-20260824-01",
      "week": "2026-08-24",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Aplicación",
      "details": "Tema indicado para la semana",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 250
    },
    {
      "id": "redes-20260824-02",
      "week": "2026-08-24",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 6",
      "details": "Asignada dentro de Aplicación",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 260
    },
    {
      "id": "redes-20260824-03",
      "week": "2026-08-24",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 7",
      "details": "Asignada dentro de Aplicación",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 270
    },
    {
      "id": "redes-20260824-04",
      "week": "2026-08-24",
      "eventDate": "",
      "subject": "redes",
      "type": "reading",
      "title": "Capítulo 2 hasta el final",
      "details": "Lectura asignada para Aplicación",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 280
    },
    {
      "id": "redes-20260824-05",
      "week": "2026-08-24",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P3 y P4 · EMAIL y DNS",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 290
    },
    {
      "id": "redes-20260824-06",
      "week": "2026-08-24",
      "eventDate": "",
      "subject": "redes",
      "type": "holiday",
      "title": "Feriado",
      "details": "Actividad del curso",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 300
    },
    {
      "id": "redes-20260824-07",
      "week": "2026-08-24",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Repaso DNS y Práctico 4",
      "details": "Actividad de clase indicada en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 310
    },
    {
      "id": "redes-20260824-08",
      "week": "2026-08-24",
      "eventDate": "",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 320
    },
    {
      "id": "redes-20260831-01",
      "week": "2026-08-31",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Transporte",
      "details": "Tema indicado para la semana",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 330
    },
    {
      "id": "redes-20260831-02",
      "week": "2026-08-31",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 8",
      "details": "Asignada dentro de Transporte",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 340
    },
    {
      "id": "redes-20260831-03",
      "week": "2026-08-31",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 9",
      "details": "Asignada dentro de Transporte",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 350
    },
    {
      "id": "redes-20260831-04",
      "week": "2026-08-31",
      "eventDate": "",
      "subject": "redes",
      "type": "reading",
      "title": "Capítulo 3 hasta 3.4",
      "details": "Lectura asignada para Transporte",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 360
    },
    {
      "id": "redes-20260831-05",
      "week": "2026-08-31",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P4",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 370
    },
    {
      "id": "redes-20260831-06",
      "week": "2026-08-31",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Repaso EMAIL y Práctico 4",
      "details": "Actividad de clase indicada en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 380
    },
    {
      "id": "redes-20260831-07",
      "week": "2026-08-31",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Repaso transporte y RDT",
      "details": "Actividad de clase indicada en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 390
    },
    {
      "id": "redes-20260831-08",
      "week": "2026-08-31",
      "eventDate": "",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 400
    },
    {
      "id": "redes-20260907-01",
      "week": "2026-09-07",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Transporte",
      "details": "Tema indicado para la semana",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 410
    },
    {
      "id": "redes-20260907-02",
      "week": "2026-09-07",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 8",
      "details": "Asignada dentro de Transporte",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 420
    },
    {
      "id": "redes-20260907-03",
      "week": "2026-09-07",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 9",
      "details": "Asignada dentro de Transporte",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 430
    },
    {
      "id": "redes-20260907-04",
      "week": "2026-09-07",
      "eventDate": "",
      "subject": "redes",
      "type": "reading",
      "title": "Capítulo 3 hasta 3.4",
      "details": "Lectura asignada para Transporte",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 440
    },
    {
      "id": "redes-20260907-05",
      "week": "2026-09-07",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P5 · RDT, control de congestión y TCP",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 450
    },
    {
      "id": "redes-20260907-06",
      "week": "2026-09-07",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "P5",
      "details": "Actividad de clase indicada en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 460
    },
    {
      "id": "redes-20260907-07",
      "week": "2026-09-07",
      "eventDate": "2026-09-11",
      "subject": "redes",
      "type": "deadline",
      "title": "Entrega del Obligatorio 1",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": true,
      "priority": "critical",
      "order": 470
    },
    {
      "id": "redes-20260907-08",
      "week": "2026-09-07",
      "eventDate": "",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 480
    },
    {
      "id": "redes-20260914-01",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Transporte",
      "details": "Tema indicado para la semana",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 490
    },
    {
      "id": "redes-20260914-02",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 10",
      "details": "Asignada dentro de Transporte",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 500
    },
    {
      "id": "redes-20260914-03",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 11",
      "details": "Asignada dentro de Transporte",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 510
    },
    {
      "id": "redes-20260914-04",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "redes",
      "type": "reading",
      "title": "Capítulo 3 hasta 3.6",
      "details": "Lectura asignada para Transporte",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 520
    },
    {
      "id": "redes-20260914-05",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P5",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 530
    },
    {
      "id": "redes-20260914-06",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "P5",
      "details": "Actividad de clase indicada en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 540
    },
    {
      "id": "redes-20260914-07",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Repaso TCP y control de congestión",
      "details": "Actividad de clase indicada en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 550
    },
    {
      "id": "redes-20260914-08",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "redes",
      "type": "defense",
      "title": "Defensas",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": true,
      "priority": "high",
      "order": 560
    },
    {
      "id": "redes-20260921-01",
      "week": "2026-09-21",
      "eventDate": "",
      "subject": "redes",
      "type": "partial-window",
      "title": "Período de parciales",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 570
    },
    {
      "id": "redes-20260928-01",
      "week": "2026-09-28",
      "eventDate": "",
      "subject": "redes",
      "type": "no-class",
      "title": "No hay clase",
      "details": "Actividad del curso",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 580
    },
    {
      "id": "redes-20260928-02",
      "week": "2026-09-28",
      "eventDate": "",
      "subject": "redes",
      "type": "partial-window",
      "title": "Período de parciales",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 590
    },
    {
      "id": "redes-20260928-03",
      "week": "2026-09-28",
      "eventDate": "2026-10-02",
      "subject": "redes",
      "type": "assignment-published",
      "title": "Publicación del Obligatorio 2",
      "details": "Plazo indicado: 6 semanas",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": true,
      "priority": "high",
      "order": 600
    },
    {
      "id": "redes-20261005-01",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Transporte",
      "details": "Tema indicado para la semana",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 610
    },
    {
      "id": "redes-20261005-02",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 11",
      "details": "Asignada dentro de Transporte",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 620
    },
    {
      "id": "redes-20261005-03",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "redes",
      "type": "reading",
      "title": "Capítulo 3 hasta el final",
      "details": "Lectura asignada para Transporte",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 630
    },
    {
      "id": "redes-20261005-04",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P5 · RDT, control de congestión y TCP",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 640
    },
    {
      "id": "redes-20261005-05",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Repaso control de congestión y P5",
      "details": "Actividad de clase indicada en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 650
    },
    {
      "id": "redes-20261005-06",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "P5",
      "details": "Actividad de clase indicada en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 660
    },
    {
      "id": "redes-20261005-07",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 670
    },
    {
      "id": "redes-20261012-01",
      "week": "2026-10-12",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Red: plano de datos",
      "details": "Tema indicado para la semana",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 680
    },
    {
      "id": "redes-20261012-02",
      "week": "2026-10-12",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 12",
      "details": "Asignada dentro de Red: plano de datos",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 690
    },
    {
      "id": "redes-20261012-03",
      "week": "2026-10-12",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 13",
      "details": "Asignada dentro de Red: plano de datos",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 700
    },
    {
      "id": "redes-20261012-04",
      "week": "2026-10-12",
      "eventDate": "",
      "subject": "redes",
      "type": "reading",
      "title": "Capítulo 4 hasta 4.3",
      "details": "Lectura asignada para Red: plano de datos",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 710
    },
    {
      "id": "redes-20261012-05",
      "week": "2026-10-12",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P6 · Direccionamiento, numeración, forwarding y LPM",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 720
    },
    {
      "id": "redes-20261012-06",
      "week": "2026-10-12",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Repaso servicios, planos, políticas y P6",
      "details": "Actividad de clase indicada en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 730
    },
    {
      "id": "redes-20261012-07",
      "week": "2026-10-12",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Repaso numeración IP y P6",
      "details": "Actividad de clase indicada en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 740
    },
    {
      "id": "redes-20261012-08",
      "week": "2026-10-12",
      "eventDate": "",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 750
    },
    {
      "id": "redes-20261019-01",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Red: IPv6",
      "details": "Tema indicado para la semana",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 760
    },
    {
      "id": "redes-20261019-02",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 14",
      "details": "Asignada dentro de Red: IPv6",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 770
    },
    {
      "id": "redes-20261019-03",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 18",
      "details": "Asignada dentro de Red: IPv6",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 780
    },
    {
      "id": "redes-20261019-04",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 19",
      "details": "Asignada dentro de Red: IPv6",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 790
    },
    {
      "id": "redes-20261019-05",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "redes",
      "type": "reading",
      "title": "Material IPv6",
      "details": "Lectura asignada para Red: IPv6",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 800
    },
    {
      "id": "redes-20261019-06",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P6",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 810
    },
    {
      "id": "redes-20261019-07",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Práctico 6",
      "details": "Actividad de clase indicada en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 820
    },
    {
      "id": "redes-20261019-08",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Práctico 6",
      "details": "Actividad de clase indicada en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 830
    },
    {
      "id": "redes-20261019-09",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 840
    },
    {
      "id": "redes-20261026-01",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Red: plano de control",
      "details": "Tema indicado para la semana",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 850
    },
    {
      "id": "redes-20261026-02",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 14",
      "details": "Asignada dentro de Red: plano de control",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 860
    },
    {
      "id": "redes-20261026-03",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 15",
      "details": "Asignada dentro de Red: plano de control",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 870
    },
    {
      "id": "redes-20261026-04",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "redes",
      "type": "reading",
      "title": "Capítulo 5 hasta 5.3",
      "details": "Lectura asignada para Red: plano de control",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 880
    },
    {
      "id": "redes-20261026-05",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P7 · Enrutamiento (DV y LS), OSPF y BGP",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 890
    },
    {
      "id": "redes-20261026-06",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Repaso algoritmos de enrutamiento",
      "details": "Actividad de clase indicada en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 900
    },
    {
      "id": "redes-20261026-07",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Repaso OSPF y BGP; Práctico 7",
      "details": "Actividad de clase indicada en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 910
    },
    {
      "id": "redes-20261026-08",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 920
    },
    {
      "id": "redes-20261102-01",
      "week": "2026-11-02",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Red: plano de control",
      "details": "Tema indicado para la semana",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 930
    },
    {
      "id": "redes-20261102-02",
      "week": "2026-11-02",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 16",
      "details": "Asignada dentro de Red: plano de control",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 940
    },
    {
      "id": "redes-20261102-03",
      "week": "2026-11-02",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 17",
      "details": "Asignada dentro de Red: plano de control",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 950
    },
    {
      "id": "redes-20261102-04",
      "week": "2026-11-02",
      "eventDate": "",
      "subject": "redes",
      "type": "reading",
      "title": "Capítulo 5 hasta el final; Multicast y Broadcast",
      "details": "Lectura asignada para Red: plano de control",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 960
    },
    {
      "id": "redes-20261102-05",
      "week": "2026-11-02",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P7",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 970
    },
    {
      "id": "redes-20261102-06",
      "week": "2026-11-02",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Práctico 7",
      "details": "Actividad de clase indicada en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 980
    },
    {
      "id": "redes-20261102-07",
      "week": "2026-11-02",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Práctico 7",
      "details": "Actividad de clase indicada en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 990
    },
    {
      "id": "redes-20261102-08",
      "week": "2026-11-02",
      "eventDate": "",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1000
    },
    {
      "id": "redes-20261109-01",
      "week": "2026-11-09",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Enlace",
      "details": "Tema indicado para la semana",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1010
    },
    {
      "id": "redes-20261109-02",
      "week": "2026-11-09",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 20",
      "details": "Asignada dentro de Enlace",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1020
    },
    {
      "id": "redes-20261109-03",
      "week": "2026-11-09",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 21",
      "details": "Asignada dentro de Enlace",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1030
    },
    {
      "id": "redes-20261109-04",
      "week": "2026-11-09",
      "eventDate": "",
      "subject": "redes",
      "type": "reading",
      "title": "Capítulo 6 hasta 6.3",
      "details": "Lectura asignada para Enlace",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1040
    },
    {
      "id": "redes-20261109-05",
      "week": "2026-11-09",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P8 y P9 · Capa de enlace",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1050
    },
    {
      "id": "redes-20261109-06",
      "week": "2026-11-09",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Repaso enlace",
      "details": "Actividad de clase indicada en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1060
    },
    {
      "id": "redes-20261109-07",
      "week": "2026-11-09",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Práctico 8",
      "details": "Actividad de clase indicada en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1070
    },
    {
      "id": "redes-20261109-08",
      "week": "2026-11-09",
      "eventDate": "2026-11-13",
      "subject": "redes",
      "type": "deadline",
      "title": "Entrega del Obligatorio 2",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": true,
      "priority": "critical",
      "order": 1080
    },
    {
      "id": "redes-20261109-09",
      "week": "2026-11-09",
      "eventDate": "",
      "subject": "redes",
      "type": "monitoring",
      "title": "Monitoreo",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1090
    },
    {
      "id": "redes-20261116-01",
      "week": "2026-11-16",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Enlace",
      "details": "Tema indicado para la semana",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1100
    },
    {
      "id": "redes-20261116-02",
      "week": "2026-11-16",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 22",
      "details": "Asignada dentro de Enlace",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1110
    },
    {
      "id": "redes-20261116-03",
      "week": "2026-11-16",
      "eventDate": "",
      "subject": "redes",
      "type": "openfing",
      "title": "Clase OpenFing 23",
      "details": "Asignada dentro de Enlace",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1120
    },
    {
      "id": "redes-20261116-04",
      "week": "2026-11-16",
      "eventDate": "",
      "subject": "redes",
      "type": "reading",
      "title": "Capítulo 6 hasta el final",
      "details": "Lectura asignada para Enlace",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1130
    },
    {
      "id": "redes-20261116-05",
      "week": "2026-11-16",
      "eventDate": "",
      "subject": "redes",
      "type": "practical",
      "title": "P9",
      "details": "Práctico asignado en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1140
    },
    {
      "id": "redes-20261116-06",
      "week": "2026-11-16",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Práctico 8 y Práctico 9",
      "details": "Actividad de clase indicada en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1150
    },
    {
      "id": "redes-20261116-07",
      "week": "2026-11-16",
      "eventDate": "",
      "subject": "redes",
      "type": "course-class",
      "title": "Práctico 9 y cierre del curso",
      "details": "Actividad de clase indicada en el cronograma",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1160
    },
    {
      "id": "redes-20261116-08",
      "week": "2026-11-16",
      "eventDate": "",
      "subject": "redes",
      "type": "defense",
      "title": "Defensas",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": true,
      "priority": "high",
      "order": 1170
    },
    {
      "id": "redes-20261123-01",
      "week": "2026-11-23",
      "eventDate": "",
      "subject": "redes",
      "type": "partial-window",
      "title": "Período de parciales",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1180
    },
    {
      "id": "redes-20261130-01",
      "week": "2026-11-30",
      "eventDate": "",
      "subject": "redes",
      "type": "partial-window",
      "title": "Período de parciales",
      "details": "",
      "source": "Cronograma Redes 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1190
    },
    {
      "id": "fuaa-20260810-01",
      "week": "2026-08-10",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 1 · Introducción al problema de aprendizaje",
      "details": "Tema 1",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1200
    },
    {
      "id": "fuaa-20260810-02",
      "week": "2026-08-10",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 2 · El problema de aprendizaje",
      "details": "Tema 2",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1210
    },
    {
      "id": "fuaa-20260810-03",
      "week": "2026-08-10",
      "eventDate": "",
      "subject": "fuaa",
      "type": "reading",
      "title": "Secciones del libro asignadas",
      "details": "Tema 1: 1.1, 1.2 · Tema 2: 1.3",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1220
    },
    {
      "id": "fuaa-20260817-01",
      "week": "2026-08-17",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 4 · El modelo lineal",
      "details": "Tema 3",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1230
    },
    {
      "id": "fuaa-20260817-02",
      "week": "2026-08-17",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 5 · Error y ruido",
      "details": "Tema 4",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1240
    },
    {
      "id": "fuaa-20260817-03",
      "week": "2026-08-17",
      "eventDate": "",
      "subject": "fuaa",
      "type": "reading",
      "title": "Secciones del libro asignadas",
      "details": "Tema 3: 3.1, 3.2, 3.4 · Tema 4: 1.4, 1.3.3",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1250
    },
    {
      "id": "fuaa-20260824-01",
      "week": "2026-08-24",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 6 · Entrenamiento versus prueba",
      "details": "Tema 5",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1260
    },
    {
      "id": "fuaa-20260824-02",
      "week": "2026-08-24",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 8 · Teoría de la generalización",
      "details": "Tema 6",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1270
    },
    {
      "id": "fuaa-20260824-03",
      "week": "2026-08-24",
      "eventDate": "",
      "subject": "fuaa",
      "type": "reading",
      "title": "Secciones del libro asignadas",
      "details": "Tema 5: 2.1, 2.1.1 · Tema 6: 2.1",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1280
    },
    {
      "id": "fuaa-20260831-01",
      "week": "2026-08-31",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 9 · La dimensión VC",
      "details": "Tema 7",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1290
    },
    {
      "id": "fuaa-20260831-02",
      "week": "2026-08-31",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 10 · Compromiso sesgo-varianza",
      "details": "Tema 8",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1300
    },
    {
      "id": "fuaa-20260831-03",
      "week": "2026-08-31",
      "eventDate": "",
      "subject": "fuaa",
      "type": "reading",
      "title": "Secciones del libro asignadas",
      "details": "Tema 7: 2.2 · Tema 8: 2.3",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1310
    },
    {
      "id": "fuaa-20260907-01",
      "week": "2026-09-07",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 12 · El modelo lineal II",
      "details": "Tema 9",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1320
    },
    {
      "id": "fuaa-20260907-02",
      "week": "2026-09-07",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 13 · Sobreajuste",
      "details": "Tema 10",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1330
    },
    {
      "id": "fuaa-20260907-03",
      "week": "2026-09-07",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 14 · Regularización",
      "details": "Tema 11",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1340
    },
    {
      "id": "fuaa-20260907-04",
      "week": "2026-09-07",
      "eventDate": "",
      "subject": "fuaa",
      "type": "reading",
      "title": "Secciones del libro asignadas",
      "details": "Tema 9: 3.3 · Tema 10: 4.1 · Tema 11: 4.2",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1350
    },
    {
      "id": "fuaa-20260914-01",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 16 · Validación",
      "details": "Tema 12",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1360
    },
    {
      "id": "fuaa-20260914-02",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "fuaa",
      "type": "reading",
      "title": "Secciones del libro asignadas",
      "details": "Tema 12: 4.3",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1370
    },
    {
      "id": "fuaa-20261005-01",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 17 · Epílogo de los fundamentos teóricos",
      "details": "Tema 13",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1380
    },
    {
      "id": "fuaa-20261005-02",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 18 · Perceptrón multicapa",
      "details": "Tema 14",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1390
    },
    {
      "id": "fuaa-20261005-03",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 19 · Redes neuronales",
      "details": "Tema 15",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1400
    },
    {
      "id": "fuaa-20261005-04",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "fuaa",
      "type": "reading",
      "title": "Secciones del libro asignadas",
      "details": "Tema 13: 5.1, 5.2, 5.3 · Tema 14: 7.1, 7.2 · Tema 15: 7.3, 7.4, 7.5, 7.6",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1410
    },
    {
      "id": "fuaa-20261019-01",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 22 · Máquinas de vectores de soporte",
      "details": "Tema 16",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1420
    },
    {
      "id": "fuaa-20261019-02",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 23 · Métodos de Kernel",
      "details": "Tema 17",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1430
    },
    {
      "id": "fuaa-20261019-03",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "fuaa",
      "type": "reading",
      "title": "Secciones del libro asignadas",
      "details": "Tema 16: 8.1, 8.2 · Tema 17: 8.3, 8.4",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1440
    },
    {
      "id": "fuaa-20261026-01",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 25 · Métodos basados en similitud",
      "details": "Tema 18",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1450
    },
    {
      "id": "fuaa-20261026-02",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 26 · Aprendizaje no supervisado",
      "details": "Tema 19",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1460
    },
    {
      "id": "fuaa-20261026-03",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "fuaa",
      "type": "reading",
      "title": "Secciones del libro asignadas",
      "details": "Tema 18: 6.1, 6.2, 6.3 · Tema 19: 6.3, 6.4",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1470
    },
    {
      "id": "fuaa-20261109-01",
      "week": "2026-11-09",
      "eventDate": "",
      "subject": "fuaa",
      "type": "openfing",
      "title": "OpenFing 28 · Ingeniería de características",
      "details": "Tema 20",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1480
    },
    {
      "id": "fuaa-20260803-01",
      "week": "2026-08-03",
      "eventDate": "",
      "subject": "fuaa",
      "type": "course-class",
      "title": "Presentación",
      "details": "Tema 1",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1490
    },
    {
      "id": "fuaa-20260803-02",
      "week": "2026-08-03",
      "eventDate": "",
      "subject": "fuaa",
      "type": "workshop",
      "title": "Consultas / Taller",
      "details": "P0, Python y NumPy",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1500
    },
    {
      "id": "fuaa-20260810-04",
      "week": "2026-08-10",
      "eventDate": "",
      "subject": "fuaa",
      "type": "discussion",
      "title": "Discusión 1 y 2",
      "details": "Temas 1 y 2",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1510
    },
    {
      "id": "fuaa-20260810-05",
      "week": "2026-08-10",
      "eventDate": "",
      "subject": "fuaa",
      "type": "control",
      "title": "Control 0",
      "details": "Temas 1 y 2",
      "source": "FuAA 2026",
      "fixed": true,
      "important": true,
      "priority": "high",
      "order": 1520
    },
    {
      "id": "fuaa-20260810-06",
      "week": "2026-08-10",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 1",
      "details": "Temas 1 y 2",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1530
    },
    {
      "id": "fuaa-20260810-07",
      "week": "2026-08-10",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP01",
      "details": "Vinculado al Práctico 1",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1540
    },
    {
      "id": "fuaa-20260817-04",
      "week": "2026-08-17",
      "eventDate": "",
      "subject": "fuaa",
      "type": "discussion",
      "title": "Discusión 3 y 4",
      "details": "Temas 3 y 4",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1550
    },
    {
      "id": "fuaa-20260817-05",
      "week": "2026-08-17",
      "eventDate": "",
      "subject": "fuaa",
      "type": "control",
      "title": "Control 1",
      "details": "Temas 1, 2 y 3",
      "source": "FuAA 2026",
      "fixed": true,
      "important": true,
      "priority": "high",
      "order": 1560
    },
    {
      "id": "fuaa-20260817-06",
      "week": "2026-08-17",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 2",
      "details": "Temas 3, 4 y 5",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1570
    },
    {
      "id": "fuaa-20260817-07",
      "week": "2026-08-17",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP02",
      "details": "Vinculado al Práctico 2",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1580
    },
    {
      "id": "fuaa-20260824-04",
      "week": "2026-08-24",
      "eventDate": "",
      "subject": "fuaa",
      "type": "discussion",
      "title": "Discusión 5 y 6",
      "details": "Temas 5 y 6",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1590
    },
    {
      "id": "fuaa-20260824-05",
      "week": "2026-08-24",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 2",
      "details": "Temas 3, 4 y 5",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1600
    },
    {
      "id": "fuaa-20260824-06",
      "week": "2026-08-24",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP03",
      "details": "Vinculado al Práctico 2",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1610
    },
    {
      "id": "fuaa-20260831-04",
      "week": "2026-08-31",
      "eventDate": "",
      "subject": "fuaa",
      "type": "discussion",
      "title": "Discusión 7 y 8",
      "details": "Temas 7 y 8",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1620
    },
    {
      "id": "fuaa-20260831-05",
      "week": "2026-08-31",
      "eventDate": "",
      "subject": "fuaa",
      "type": "control",
      "title": "Control 2",
      "details": "Temas 4, 5, 6 y 7",
      "source": "FuAA 2026",
      "fixed": true,
      "important": true,
      "priority": "high",
      "order": 1630
    },
    {
      "id": "fuaa-20260831-06",
      "week": "2026-08-31",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 3",
      "details": "Temas 6, 7, 8 y 9",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1640
    },
    {
      "id": "fuaa-20260831-07",
      "week": "2026-08-31",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP04",
      "details": "Vinculado al Práctico 3",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1650
    },
    {
      "id": "fuaa-20260907-05",
      "week": "2026-09-07",
      "eventDate": "",
      "subject": "fuaa",
      "type": "discussion",
      "title": "Discusión 9, 10 y 11",
      "details": "Temas 9, 10 y 11",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1660
    },
    {
      "id": "fuaa-20260907-06",
      "week": "2026-09-07",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 3 / Práctico 4",
      "details": "Temas 6, 7, 8 y 9",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1670
    },
    {
      "id": "fuaa-20260907-07",
      "week": "2026-09-07",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP05",
      "details": "Vinculado a los prácticos",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1680
    },
    {
      "id": "fuaa-20260914-03",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "fuaa",
      "type": "discussion",
      "title": "Discusión / Práctico 4",
      "details": "Tema 12",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1690
    },
    {
      "id": "fuaa-20260914-04",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "fuaa",
      "type": "control",
      "title": "Control 3",
      "details": "Temas 8, 9, 10 y 11",
      "source": "FuAA 2026",
      "fixed": true,
      "important": true,
      "priority": "high",
      "order": 1700
    },
    {
      "id": "fuaa-20260914-05",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 4",
      "details": "Temas 10, 11 y 12",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1710
    },
    {
      "id": "fuaa-20260914-06",
      "week": "2026-09-14",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP06",
      "details": "Vinculado al Práctico 4",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1720
    },
    {
      "id": "fuaa-20260921-01",
      "week": "2026-09-21",
      "eventDate": "",
      "subject": "fuaa",
      "type": "consultation",
      "title": "Consultas / Taller de parciales",
      "details": "",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1730
    },
    {
      "id": "fuaa-20260921-02",
      "week": "2026-09-21",
      "eventDate": "2026-09-23",
      "subject": "fuaa",
      "type": "partial",
      "title": "Primer parcial",
      "details": "",
      "source": "FuAA 2026",
      "fixed": true,
      "important": true,
      "priority": "critical",
      "order": 1740
    },
    {
      "id": "fuaa-20260928-01",
      "week": "2026-09-28",
      "eventDate": "",
      "subject": "fuaa",
      "type": "partial-window",
      "title": "Período de parciales",
      "details": "",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1750
    },
    {
      "id": "fuaa-20261005-05",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "fuaa",
      "type": "discussion",
      "title": "Discusión 13, 14 y 15",
      "details": "Temas 13, 14 y 15",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1760
    },
    {
      "id": "fuaa-20261005-06",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 5 / scikit-learn",
      "details": "Temas 14 y 15",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1770
    },
    {
      "id": "fuaa-20261005-07",
      "week": "2026-10-05",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP07",
      "details": "Vinculado al Práctico 5",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1780
    },
    {
      "id": "fuaa-20261012-01",
      "week": "2026-10-12",
      "eventDate": "",
      "subject": "fuaa",
      "type": "holiday",
      "title": "Feriado",
      "details": "",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1790
    },
    {
      "id": "fuaa-20261012-02",
      "week": "2026-10-12",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 5",
      "details": "Temas 14 y 15",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1800
    },
    {
      "id": "fuaa-20261012-03",
      "week": "2026-10-12",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP08",
      "details": "Vinculado al Práctico 5",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1810
    },
    {
      "id": "fuaa-20261019-04",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "fuaa",
      "type": "discussion",
      "title": "Discusión 16 y 17",
      "details": "Temas 16 y 17",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1820
    },
    {
      "id": "fuaa-20261019-05",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "fuaa",
      "type": "control",
      "title": "Control 4",
      "details": "Temas 14 y 15",
      "source": "FuAA 2026",
      "fixed": true,
      "important": true,
      "priority": "high",
      "order": 1830
    },
    {
      "id": "fuaa-20261019-06",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 6",
      "details": "Temas 16 y 17",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1840
    },
    {
      "id": "fuaa-20261019-07",
      "week": "2026-10-19",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP09",
      "details": "Vinculado al Práctico 6",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1850
    },
    {
      "id": "fuaa-20261026-04",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "fuaa",
      "type": "discussion",
      "title": "Discusión 18 y 19",
      "details": "Temas 18 y 19",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1860
    },
    {
      "id": "fuaa-20261026-05",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "fuaa",
      "type": "control",
      "title": "Control 5",
      "details": "Temas 16 y 17",
      "source": "FuAA 2026",
      "fixed": true,
      "important": true,
      "priority": "high",
      "order": 1870
    },
    {
      "id": "fuaa-20261026-06",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 6",
      "details": "Temas 16 y 17",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1880
    },
    {
      "id": "fuaa-20261026-07",
      "week": "2026-10-26",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP10",
      "details": "Vinculado al Práctico 6",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1890
    },
    {
      "id": "fuaa-20261102-01",
      "week": "2026-11-02",
      "eventDate": "",
      "subject": "fuaa",
      "type": "holiday",
      "title": "Feriado",
      "details": "",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1900
    },
    {
      "id": "fuaa-20261102-02",
      "week": "2026-11-02",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 7",
      "details": "Temas 18, 19 y 20",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1910
    },
    {
      "id": "fuaa-20261102-03",
      "week": "2026-11-02",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP11",
      "details": "Vinculado al Práctico 7",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1920
    },
    {
      "id": "fuaa-20261109-02",
      "week": "2026-11-09",
      "eventDate": "",
      "subject": "fuaa",
      "type": "discussion",
      "title": "Discusión 20",
      "details": "Tema 20",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1930
    },
    {
      "id": "fuaa-20261109-03",
      "week": "2026-11-09",
      "eventDate": "",
      "subject": "fuaa",
      "type": "practical",
      "title": "Práctico 7",
      "details": "Temas 18, 19 y 20",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1940
    },
    {
      "id": "fuaa-20261109-04",
      "week": "2026-11-09",
      "eventDate": "",
      "subject": "fuaa",
      "type": "control",
      "title": "Control 6",
      "details": "Temas 18, 19 y 20",
      "source": "FuAA 2026",
      "fixed": true,
      "important": true,
      "priority": "high",
      "order": 1950
    },
    {
      "id": "fuaa-20261109-05",
      "week": "2026-11-09",
      "eventDate": "",
      "subject": "fuaa",
      "type": "questionnaire",
      "title": "Cuestionario CP12",
      "details": "Vinculado al Práctico 7",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1960
    },
    {
      "id": "fuaa-20261116-01",
      "week": "2026-11-16",
      "eventDate": "",
      "subject": "fuaa",
      "type": "consultation",
      "title": "Consultas",
      "details": "Ética",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1970
    },
    {
      "id": "fuaa-20261116-02",
      "week": "2026-11-16",
      "eventDate": "",
      "subject": "fuaa",
      "type": "consultation",
      "title": "Consultas finales",
      "details": "",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 1980
    },
    {
      "id": "fuaa-20261123-01",
      "week": "2026-11-23",
      "eventDate": "2026-11-23",
      "subject": "fuaa",
      "type": "partial",
      "title": "Segundo parcial",
      "details": "",
      "source": "FuAA 2026",
      "fixed": true,
      "important": true,
      "priority": "critical",
      "order": 1990
    },
    {
      "id": "fuaa-20261123-02",
      "week": "2026-11-23",
      "eventDate": "",
      "subject": "fuaa",
      "type": "partial-window",
      "title": "Período de parciales",
      "details": "",
      "source": "FuAA 2026",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2000
    },
    {
      "id": "fbd-undated-01",
      "week": "",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Clase OpenFing 1",
      "details": "Presentación del curso. Introducción y conceptos generales",
      "source": "Lista OpenFing proporcionada",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2010
    },
    {
      "id": "fbd-undated-02",
      "week": "",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Clase OpenFing 2",
      "details": "Diseño conceptual",
      "source": "Lista OpenFing proporcionada",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2020
    },
    {
      "id": "fbd-undated-03",
      "week": "",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Clase OpenFing 3",
      "details": "Diseño conceptual. Ejemplo",
      "source": "Lista OpenFing proporcionada",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2030
    },
    {
      "id": "fbd-undated-04",
      "week": "",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Clase OpenFing 4",
      "details": "Diseño conceptual. Modelo relacional",
      "source": "Lista OpenFing proporcionada",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2040
    },
    {
      "id": "fbd-undated-05",
      "week": "",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Clase OpenFing 5",
      "details": "Álgebra relacional",
      "source": "Lista OpenFing proporcionada",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2050
    },
    {
      "id": "fbd-undated-06",
      "week": "",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Clase OpenFing 6",
      "details": "Álgebra relacional. Ejemplos",
      "source": "Lista OpenFing proporcionada",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2060
    },
    {
      "id": "fbd-undated-07",
      "week": "",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Clase OpenFing 7",
      "details": "Cálculo Relacional",
      "source": "Lista OpenFing proporcionada",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2070
    },
    {
      "id": "fbd-undated-08",
      "week": "",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Clase OpenFing 8",
      "details": "Cálculo Relacional. Ejemplos",
      "source": "Lista OpenFing proporcionada",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2080
    },
    {
      "id": "fbd-undated-09",
      "week": "",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Clase OpenFing 9",
      "details": "Lenguajes de Consulta - SQL",
      "source": "Lista OpenFing proporcionada",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2090
    },
    {
      "id": "fbd-undated-10",
      "week": "",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Clase OpenFing 10",
      "details": "Práctico de SQL",
      "source": "Lista OpenFing proporcionada",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2100
    },
    {
      "id": "fbd-undated-11",
      "week": "",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Clase OpenFing 11",
      "details": "Diseño relacional. Dependencias funcionales - 1",
      "source": "Lista OpenFing proporcionada",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2110
    },
    {
      "id": "fbd-undated-12",
      "week": "",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Clase OpenFing 12",
      "details": "Diseño relacional. Dependencias funcionales - 2",
      "source": "Lista OpenFing proporcionada",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2120
    },
    {
      "id": "fbd-undated-13",
      "week": "",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Clase OpenFing 13",
      "details": "Normalización - 1",
      "source": "Lista OpenFing proporcionada",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2130
    },
    {
      "id": "fbd-undated-14",
      "week": "",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Clase OpenFing 14",
      "details": "Normalización - 2",
      "source": "Lista OpenFing proporcionada",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2140
    },
    {
      "id": "fbd-undated-15",
      "week": "",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Clase OpenFing 15",
      "details": "Dependencias Multivaluadas",
      "source": "Lista OpenFing proporcionada",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2150
    },
    {
      "id": "fbd-undated-16",
      "week": "",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Clase OpenFing 16",
      "details": "Pasaje de MER a MR",
      "source": "Lista OpenFing proporcionada",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2160
    },
    {
      "id": "fbd-undated-17",
      "week": "",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Clase OpenFing 17",
      "details": "Ejercicios MER-MR y Estrategias BDMS",
      "source": "Lista OpenFing proporcionada",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2170
    },
    {
      "id": "fbd-undated-18",
      "week": "",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Clase OpenFing 18",
      "details": "Procesamiento y Optimización de Consultas",
      "source": "Lista OpenFing proporcionada",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2180
    },
    {
      "id": "fbd-undated-19",
      "week": "",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Clase OpenFing 19",
      "details": "Optimización de Consultas",
      "source": "Lista OpenFing proporcionada",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2190
    },
    {
      "id": "fbd-undated-20",
      "week": "",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Clase OpenFing 20",
      "details": "Transacciones y Concurrencia",
      "source": "Lista OpenFing proporcionada",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2200
    },
    {
      "id": "fbd-undated-21",
      "week": "",
      "eventDate": "",
      "subject": "fbd",
      "type": "openfing",
      "title": "Clase OpenFing 21",
      "details": "Concurrencia y Recuperación",
      "source": "Lista OpenFing proporcionada",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2210
    },
    {
      "id": "pln-undated-01",
      "week": "",
      "eventDate": "",
      "subject": "pln",
      "type": "notice",
      "title": "Cronograma pendiente de publicación",
      "details": "Todavía no hay clases ni fechas para cargar.",
      "source": "Pendiente",
      "fixed": true,
      "important": false,
      "priority": "normal",
      "order": 2220
    }
  ]
};
